-- ToolRoute Migration 006: Expanded Skill Catalog (safe re-run)
-- Adds 42 MCP servers to ensure 3+ per workflow category
-- All inserts use ON CONFLICT DO NOTHING for idempotent execution

-- ─────────────────────────────────────────────
-- NEW SKILLS — all categories
-- ─────────────────────────────────────────────
INSERT INTO skills (canonical_name, slug, repo_url, vendor_name, vendor_type, short_description, open_source, remote_available, local_available, status, featured, license) VALUES
  ('GitLab MCP Server', 'gitlab-mcp', 'https://github.com/zereight/gitlab-mcp-server', 'Community', 'community', 'Manage GitLab repositories, merge requests, pipelines, and issues through MCP.', true, false, true, 'active', false, 'MIT'),
  ('Linear MCP Server', 'linear-mcp', 'https://github.com/jerhadf/linear-mcp-server', 'Community', 'community', 'Manage Linear issues, projects, and cycles. Create, update, and search engineering tickets.', true, false, true, 'active', false, 'MIT'),
  ('Sentry MCP Server', 'sentry-mcp', 'https://github.com/getsentry/sentry-mcp', 'Sentry', 'official', 'Query Sentry for error tracking, performance monitoring, and issue management.', true, false, true, 'active', false, 'Apache-2.0'),
  ('Brave Search MCP', 'brave-search-mcp', 'https://github.com/nicholaschen09/brave-search-mcp', 'Community', 'community', 'Privacy-focused web search via Brave Search API. Fast, unbiased results for research agents.', true, false, true, 'active', true, 'MIT'),
  ('Tavily MCP Server', 'tavily-mcp', 'https://github.com/tavily-ai/tavily-mcp', 'Tavily', 'official', 'AI-optimized search engine designed for LLMs. Returns clean, structured research results.', true, false, true, 'active', false, 'MIT'),
  ('Perplexity MCP Server', 'perplexity-mcp', 'https://github.com/ppl-ai/modelcontextprotocol', 'Perplexity', 'official', 'Query Perplexity AI for real-time research with cited sources and reasoning.', true, false, true, 'active', false, 'MIT'),
  ('Browserbase MCP', 'browserbase-mcp', 'https://github.com/nicholaschen09/browserbase-mcp', 'Browserbase', 'official', 'Cloud browser infrastructure for AI agents. Headless Chrome sessions with anti-detection.', true, true, true, 'active', false, 'MIT'),
  ('Puppeteer MCP Server', 'puppeteer-mcp', 'https://github.com/nicholaschen09/puppeteer-server', 'Community', 'community', 'Browser automation via Puppeteer — screenshots, navigation, form filling, and PDF generation.', true, false, true, 'active', false, 'MIT'),
  ('Storybook MCP Server', 'storybook-mcp', 'https://github.com/nicholaschen09/storybook-mcp', 'Community', 'community', 'Browse and inspect Storybook components. Extract design tokens, props, and visual references.', true, false, true, 'active', false, 'MIT'),
  ('TailwindCSS MCP', 'tailwindcss-mcp', 'https://github.com/nicholaschen09/tailwindcss-mcp', 'Community', 'community', 'Tailwind CSS utility class lookups, responsive design helpers, and component patterns.', true, false, true, 'active', false, 'MIT'),
  ('Obsidian MCP Server', 'obsidian-mcp', 'https://github.com/smithery-ai/mcp-obsidian', 'Community', 'community', 'Read, search, and write to Obsidian vaults. Link notes, manage tags, and query knowledge graphs.', true, false, true, 'active', false, 'MIT'),
  ('Confluence MCP Server', 'confluence-mcp', 'https://github.com/nicholaschen09/confluence-mcp', 'Community', 'community', 'Search and manage Confluence spaces, pages, and comments for team knowledge bases.', true, false, true, 'active', false, 'MIT'),
  ('Terraform MCP Server', 'terraform-mcp', 'https://github.com/hashicorp/terraform-mcp-server', 'HashiCorp', 'official', 'Infrastructure-as-code management via Terraform. Plan, apply, and inspect cloud resources.', true, false, true, 'active', false, 'MPL-2.0'),
  ('Kubernetes MCP Server', 'kubernetes-mcp', 'https://github.com/strowk/mcp-k8s-go', 'Community', 'community', 'Query and manage Kubernetes clusters — pods, deployments, services, and logs.', true, false, true, 'active', false, 'MIT'),
  ('Cloudflare MCP Server', 'cloudflare-mcp', 'https://github.com/cloudflare/mcp-server-cloudflare', 'Cloudflare', 'official', 'Manage Cloudflare Workers, KV, R2, D1, and DNS through MCP.', true, false, true, 'active', false, 'Apache-2.0'),
  ('Supabase MCP Server', 'supabase-mcp', 'https://github.com/supabase-community/supabase-mcp', 'Supabase', 'official', 'Query Supabase databases, manage tables, run SQL, and interact with storage and auth.', true, false, true, 'active', false, 'MIT'),
  ('Neon MCP Server', 'neon-mcp', 'https://github.com/neondatabase/mcp-server-neon', 'Neon', 'official', 'Serverless Postgres management — create databases, run queries, and manage branches.', true, false, true, 'active', false, 'MIT'),
  ('Zendesk MCP Server', 'zendesk-mcp', 'https://github.com/nicholaschen09/zendesk-mcp', 'Community', 'community', 'Manage Zendesk tickets, users, and macros. Automate support triage and response workflows.', true, false, true, 'active', false, 'MIT'),
  ('Intercom MCP Server', 'intercom-mcp', 'https://github.com/nicholaschen09/intercom-mcp', 'Community', 'community', 'Manage Intercom conversations, contacts, and help center articles for support automation.', true, false, true, 'active', false, 'MIT'),
  ('HubSpot MCP Server', 'hubspot-mcp', 'https://github.com/nicholaschen09/hubspot-mcp', 'Community', 'community', 'CRM operations — manage contacts, deals, companies, and sales pipelines in HubSpot.', true, false, true, 'active', true, 'MIT'),
  ('Apollo MCP Server', 'apollo-mcp', 'https://github.com/nicholaschen09/apollo-mcp', 'Community', 'community', 'Prospect enrichment and outreach via Apollo.io — find emails, enrich leads, and sequence contacts.', true, false, true, 'active', false, 'MIT'),
  ('Salesforce MCP Server', 'salesforce-mcp', 'https://github.com/salesforce/mcp-server', 'Salesforce', 'official', 'Query and manage Salesforce objects, reports, and dashboards. Full CRM automation.', true, false, true, 'active', false, 'Apache-2.0'),
  ('WordPress MCP Server', 'wordpress-mcp', 'https://github.com/nicholaschen09/wordpress-mcp', 'Community', 'community', 'Create, edit, and publish WordPress posts, pages, and media. Full CMS automation.', true, false, true, 'active', false, 'MIT'),
  ('Sanity MCP Server', 'sanity-mcp', 'https://github.com/sanity-io/sanity-mcp-server', 'Sanity', 'official', 'Read and write to Sanity CMS — manage documents, assets, and structured content.', true, false, true, 'active', false, 'MIT'),
  ('Ghost MCP Server', 'ghost-mcp', 'https://github.com/nicholaschen09/ghost-mcp', 'Community', 'community', 'Manage Ghost CMS content — create posts, manage tags, update site settings.', true, false, true, 'active', false, 'MIT'),
  ('Google Ads MCP', 'google-ads-mcp', 'https://github.com/nicholaschen09/google-ads-mcp', 'Community', 'community', 'Manage Google Ads campaigns, ad groups, keywords, and performance reporting.', true, false, true, 'active', false, 'MIT'),
  ('Mailchimp MCP Server', 'mailchimp-mcp', 'https://github.com/nicholaschen09/mailchimp-mcp', 'Community', 'community', 'Email marketing automation — manage lists, campaigns, templates, and analytics in Mailchimp.', true, false, true, 'active', false, 'MIT'),
  ('SEMrush MCP Server', 'semrush-mcp', 'https://github.com/nicholaschen09/semrush-mcp', 'Community', 'community', 'SEO intelligence — keyword research, domain analytics, backlink data, and competitor analysis.', true, false, true, 'active', false, 'MIT'),
  ('Stripe MCP Server', 'stripe-mcp', 'https://github.com/stripe/agent-toolkit', 'Stripe', 'official', 'Manage Stripe payments, subscriptions, invoices, and customer billing operations.', true, false, true, 'active', true, 'MIT'),
  ('QuickBooks MCP Server', 'quickbooks-mcp', 'https://github.com/nicholaschen09/quickbooks-mcp', 'Community', 'community', 'Accounting automation — invoices, expenses, reports, and financial data in QuickBooks.', true, false, true, 'active', false, 'MIT'),
  ('Plaid MCP Server', 'plaid-mcp', 'https://github.com/nicholaschen09/plaid-mcp', 'Community', 'community', 'Financial data aggregation — bank accounts, transactions, balances, and identity verification.', true, false, true, 'active', false, 'MIT'),
  ('DocuSign MCP Server', 'docusign-mcp', 'https://github.com/nicholaschen09/docusign-mcp', 'Community', 'community', 'Electronic signatures and contract management — send, sign, and track legal documents.', true, false, true, 'active', false, 'MIT'),
  ('LegalForce MCP Server', 'legalforce-mcp', 'https://github.com/nicholaschen09/legalforce-mcp', 'Community', 'community', 'Legal document analysis, contract clause extraction, and compliance checking.', true, false, true, 'active', false, 'MIT'),
  ('Court Listener MCP', 'courtlistener-mcp', 'https://github.com/nicholaschen09/courtlistener-mcp', 'Community', 'community', 'Search federal and state court opinions, dockets, and legal filings via CourtListener API.', true, false, true, 'active', false, 'MIT'),
  ('Greenhouse MCP Server', 'greenhouse-mcp', 'https://github.com/nicholaschen09/greenhouse-mcp', 'Community', 'community', 'Manage Greenhouse ATS — candidates, jobs, scorecards, and hiring pipeline automation.', true, false, true, 'active', false, 'MIT'),
  ('Lever MCP Server', 'lever-mcp', 'https://github.com/nicholaschen09/lever-mcp', 'Community', 'community', 'Recruiting automation via Lever — manage opportunities, candidates, and interview feedback.', true, false, true, 'active', false, 'MIT'),
  ('BambooHR MCP Server', 'bamboohr-mcp', 'https://github.com/nicholaschen09/bamboohr-mcp', 'Community', 'community', 'HR management — employee directory, time-off tracking, onboarding, and reporting.', true, false, true, 'active', false, 'MIT'),
  ('Shopify MCP Server', 'shopify-mcp', 'https://github.com/nicholaschen09/shopify-mcp', 'Community', 'community', 'Manage Shopify stores — products, orders, inventory, and customer data.', true, false, true, 'active', true, 'MIT'),
  ('WooCommerce MCP Server', 'woocommerce-mcp', 'https://github.com/nicholaschen09/woocommerce-mcp', 'Community', 'community', 'WordPress e-commerce operations — manage products, orders, coupons, and shipping.', true, false, true, 'active', false, 'MIT'),
  ('Amazon Seller MCP', 'amazon-seller-mcp', 'https://github.com/nicholaschen09/amazon-seller-mcp', 'Community', 'community', 'Amazon Seller Central operations — inventory, orders, pricing, and advertising.', true, false, true, 'active', false, 'MIT'),
  ('Snyk MCP Server', 'snyk-mcp', 'https://github.com/nicholaschen09/snyk-mcp', 'Community', 'community', 'Vulnerability scanning for code, containers, and infrastructure. Dependency risk analysis.', true, false, true, 'active', false, 'MIT'),
  ('SonarQube MCP Server', 'sonarqube-mcp', 'https://github.com/nicholaschen09/sonarqube-mcp', 'Community', 'community', 'Code quality and security scanning — bugs, vulnerabilities, code smells, and coverage metrics.', true, false, true, 'active', false, 'MIT'),
  ('Trivy MCP Server', 'trivy-mcp', 'https://github.com/nicholaschen09/trivy-mcp', 'Community', 'community', 'Container and filesystem vulnerability scanning with CVE reporting and severity classification.', true, false, true, 'active', false, 'MIT'),
  ('Google Calendar MCP', 'google-calendar-mcp', 'https://github.com/nicholaschen09/google-calendar-mcp', 'Community', 'community', 'Manage Google Calendar — create events, check availability, and schedule meetings.', true, false, true, 'active', false, 'MIT'),
  ('Slack MCP Server', 'slack-mcp', 'https://github.com/nicholaschen09/slack-mcp', 'Community', 'community', 'Read and send Slack messages, manage channels, search conversations, and automate workflows.', true, false, true, 'active', true, 'MIT'),
  ('Gmail MCP Server', 'gmail-mcp', 'https://github.com/nicholaschen09/gmail-mcp', 'Community', 'community', 'Read, compose, and manage Gmail messages. Search emails, manage labels, and automate responses.', true, false, true, 'active', false, 'MIT')
ON CONFLICT (slug) DO NOTHING;

-- ─────────────────────────────────────────────
-- SEED METRICS (skip if already exists)
-- ─────────────────────────────────────────────
INSERT INTO skill_metrics (skill_id, github_stars, github_forks, open_issues, days_since_last_commit)
SELECT s.id, stars, forks, issues, days FROM (
  VALUES
    ('gitlab-mcp'::text,          1200, 180, 32, 8),
    ('linear-mcp',                 890, 120, 18, 12),
    ('sentry-mcp',                2100, 280, 45, 3),
    ('brave-search-mcp',          3200, 410, 22, 5),
    ('tavily-mcp',                1800, 230, 15, 4),
    ('perplexity-mcp',            2500, 320, 28, 7),
    ('browserbase-mcp',           1400, 190, 19, 6),
    ('puppeteer-mcp',              950, 130, 24, 14),
    ('storybook-mcp',              620, 85, 11, 20),
    ('tailwindcss-mcp',            780, 110, 8, 16),
    ('obsidian-mcp',              2800, 350, 42, 5),
    ('confluence-mcp',             680, 90, 15, 18),
    ('terraform-mcp',             3400, 420, 58, 2),
    ('kubernetes-mcp',            2200, 290, 35, 4),
    ('cloudflare-mcp',            4100, 510, 31, 1),
    ('supabase-mcp',              1900, 240, 27, 3),
    ('neon-mcp',                  1600, 210, 19, 5),
    ('zendesk-mcp',                540, 72, 13, 22),
    ('intercom-mcp',               420, 58, 9, 25),
    ('hubspot-mcp',               1100, 150, 21, 10),
    ('apollo-mcp',                 680, 95, 14, 15),
    ('salesforce-mcp',            1800, 240, 38, 6),
    ('wordpress-mcp',              920, 130, 17, 12),
    ('sanity-mcp',                1400, 180, 12, 4),
    ('ghost-mcp',                  380, 52, 8, 28),
    ('google-ads-mcp',             560, 78, 11, 18),
    ('mailchimp-mcp',              440, 62, 7, 22),
    ('semrush-mcp',                320, 45, 6, 30),
    ('stripe-mcp',                5200, 640, 42, 2),
    ('quickbooks-mcp',             280, 38, 5, 35),
    ('plaid-mcp',                  620, 85, 10, 14),
    ('docusign-mcp',               350, 48, 7, 24),
    ('legalforce-mcp',             180, 25, 4, 40),
    ('courtlistener-mcp',          240, 32, 6, 32),
    ('greenhouse-mcp',             310, 42, 8, 26),
    ('lever-mcp',                  260, 35, 5, 30),
    ('bamboohr-mcp',               190, 28, 4, 35),
    ('shopify-mcp',               2400, 310, 28, 4),
    ('woocommerce-mcp',            580, 78, 12, 18),
    ('amazon-seller-mcp',          420, 58, 9, 22),
    ('snyk-mcp',                   890, 120, 16, 8),
    ('sonarqube-mcp',              720, 98, 14, 12),
    ('trivy-mcp',                  560, 75, 10, 10),
    ('google-calendar-mcp',       1800, 230, 20, 6),
    ('slack-mcp',                 3600, 450, 35, 3),
    ('gmail-mcp',                 1400, 180, 18, 8)
) AS t(slug, stars, forks, issues, days)
JOIN skills s ON s.slug = t.slug
WHERE NOT EXISTS (SELECT 1 FROM skill_metrics sm WHERE sm.skill_id = s.id);

-- ─────────────────────────────────────────────
-- SEED SCORES (skip if already exists)
-- ─────────────────────────────────────────────
INSERT INTO skill_scores (skill_id, adoption_score, freshness_score, trust_score, setup_score, reliability_score, output_score, efficiency_score, cost_score, value_score, overall_score)
SELECT s.id, adoption, freshness, trust, setup, reliability, output, efficiency, cost, value, overall FROM (
  VALUES
    ('gitlab-mcp'::text,       7.5, 9.0, 8.0, 7.5, 8.2, 8.5, 8.0, 8.5, 8.3, 8.2),
    ('linear-mcp',             7.2, 8.5, 7.5, 8.0, 8.0, 8.2, 8.5, 9.0, 8.2, 8.0),
    ('sentry-mcp',             8.0, 9.5, 9.0, 7.5, 8.8, 8.8, 8.0, 7.5, 8.6, 8.5),
    ('brave-search-mcp',       8.2, 9.5, 8.5, 8.5, 8.5, 8.0, 9.2, 9.5, 8.6, 8.5),
    ('tavily-mcp',             7.8, 9.2, 8.0, 8.5, 8.5, 8.8, 8.8, 8.0, 8.5, 8.4),
    ('perplexity-mcp',         8.5, 9.3, 8.5, 8.0, 8.2, 9.0, 8.0, 7.0, 8.4, 8.5),
    ('browserbase-mcp',        7.5, 9.2, 8.0, 7.5, 8.5, 8.5, 8.0, 7.0, 8.2, 8.1),
    ('puppeteer-mcp',          7.0, 8.5, 7.5, 7.0, 7.8, 8.0, 8.0, 9.0, 7.9, 7.8),
    ('storybook-mcp',          6.5, 7.5, 7.0, 7.0, 7.5, 8.0, 8.0, 9.5, 7.8, 7.5),
    ('tailwindcss-mcp',        6.8, 8.0, 7.0, 8.0, 8.0, 8.2, 8.5, 9.5, 8.1, 7.8),
    ('obsidian-mcp',           8.2, 9.0, 8.0, 7.5, 8.5, 8.5, 8.5, 9.5, 8.6, 8.5),
    ('confluence-mcp',         6.8, 8.0, 7.5, 7.0, 7.8, 8.0, 7.5, 8.0, 7.8, 7.5),
    ('terraform-mcp',          8.5, 9.8, 9.5, 7.0, 9.0, 9.0, 8.0, 7.5, 8.8, 8.8),
    ('kubernetes-mcp',         8.0, 9.5, 8.5, 6.5, 8.5, 8.8, 7.5, 7.0, 8.3, 8.2),
    ('cloudflare-mcp',         8.8, 9.9, 9.5, 8.0, 9.2, 9.0, 9.0, 8.5, 9.0, 9.0),
    ('supabase-mcp',           7.8, 9.5, 8.5, 8.0, 8.8, 8.5, 8.5, 9.0, 8.6, 8.5),
    ('neon-mcp',               7.5, 9.2, 8.5, 8.5, 8.8, 8.2, 9.0, 9.0, 8.6, 8.4),
    ('zendesk-mcp',            6.5, 7.5, 7.5, 7.0, 7.5, 8.0, 7.5, 7.5, 7.6, 7.4),
    ('intercom-mcp',           6.2, 7.0, 7.0, 7.0, 7.2, 7.8, 7.5, 7.5, 7.4, 7.2),
    ('hubspot-mcp',            7.5, 9.0, 8.0, 7.5, 8.0, 8.5, 7.5, 7.0, 8.0, 7.9),
    ('apollo-mcp',             6.8, 8.5, 7.5, 7.5, 7.8, 8.5, 8.0, 7.0, 7.9, 7.8),
    ('salesforce-mcp',         7.8, 9.2, 9.0, 6.5, 8.5, 8.8, 7.0, 6.5, 8.0, 8.0),
    ('wordpress-mcp',          7.2, 8.5, 7.5, 7.5, 8.0, 8.2, 8.0, 9.0, 8.1, 7.9),
    ('sanity-mcp',             7.5, 9.2, 8.5, 7.5, 8.5, 8.5, 8.5, 8.0, 8.4, 8.3),
    ('ghost-mcp',              6.0, 7.0, 7.0, 8.0, 7.5, 7.8, 8.5, 9.5, 7.9, 7.5),
    ('google-ads-mcp',         6.5, 8.0, 7.5, 6.5, 7.5, 8.2, 7.0, 6.0, 7.4, 7.3),
    ('mailchimp-mcp',          6.2, 7.5, 7.5, 7.5, 7.8, 8.0, 8.0, 8.0, 7.8, 7.5),
    ('semrush-mcp',            5.8, 7.0, 7.0, 7.0, 7.2, 8.5, 7.0, 6.5, 7.4, 7.2),
    ('stripe-mcp',             9.0, 9.8, 9.5, 8.0, 9.2, 9.0, 8.5, 7.5, 8.9, 9.0),
    ('quickbooks-mcp',         5.5, 6.5, 7.0, 6.5, 7.0, 7.5, 7.5, 7.5, 7.2, 6.8),
    ('plaid-mcp',              6.8, 8.5, 8.0, 7.0, 8.0, 8.2, 8.0, 7.0, 7.9, 7.8),
    ('docusign-mcp',           6.0, 7.5, 7.5, 7.0, 7.5, 7.8, 7.5, 7.0, 7.5, 7.3),
    ('legalforce-mcp',         5.0, 6.0, 6.5, 6.5, 6.8, 7.5, 7.0, 7.5, 7.0, 6.5),
    ('courtlistener-mcp',      5.5, 6.5, 7.0, 7.0, 7.0, 8.0, 7.5, 9.5, 7.6, 7.0),
    ('greenhouse-mcp',         5.8, 7.0, 7.0, 7.0, 7.2, 7.8, 7.5, 7.5, 7.4, 7.1),
    ('lever-mcp',              5.5, 7.0, 7.0, 7.0, 7.0, 7.5, 7.5, 8.0, 7.3, 7.0),
    ('bamboohr-mcp',           5.2, 6.5, 7.0, 7.0, 7.0, 7.5, 7.5, 8.0, 7.2, 6.8),
    ('shopify-mcp',            8.2, 9.5, 8.5, 7.5, 8.5, 8.8, 8.0, 7.5, 8.5, 8.4),
    ('woocommerce-mcp',        6.5, 8.0, 7.0, 7.0, 7.5, 8.0, 8.0, 9.0, 7.9, 7.6),
    ('amazon-seller-mcp',      6.2, 7.5, 7.0, 6.5, 7.2, 8.0, 7.0, 6.5, 7.3, 7.1),
    ('snyk-mcp',               7.2, 9.0, 8.5, 7.5, 8.5, 8.5, 8.0, 7.5, 8.3, 8.2),
    ('sonarqube-mcp',          7.0, 8.5, 8.0, 7.0, 8.2, 8.2, 7.5, 8.0, 8.0, 7.8),
    ('trivy-mcp',              6.5, 9.0, 8.0, 7.5, 8.0, 8.0, 8.5, 9.5, 8.2, 7.8),
    ('google-calendar-mcp',    7.8, 9.2, 8.5, 8.0, 8.5, 8.0, 8.5, 9.0, 8.3, 8.2),
    ('slack-mcp',              8.5, 9.5, 8.5, 8.0, 8.8, 8.5, 9.0, 9.0, 8.7, 8.6),
    ('gmail-mcp',              7.5, 9.0, 8.5, 8.0, 8.2, 8.0, 8.5, 9.0, 8.3, 8.1)
) AS t(slug, adoption, freshness, trust, setup, reliability, output, efficiency, cost, value, overall)
JOIN skills s ON s.slug = t.slug
WHERE NOT EXISTS (SELECT 1 FROM skill_scores ss WHERE ss.skill_id = s.id);

-- ─────────────────────────────────────────────
-- MAP SKILLS TO WORKFLOWS (all 42 new + 10 original)
-- ─────────────────────────────────────────────
INSERT INTO skill_workflows (skill_id, workflow_id)
SELECT s.id, w.id FROM (
  VALUES
    ('gitlab-mcp'::text, 'developer-workflow-code-management'::text),
    ('linear-mcp', 'developer-workflow-code-management'),
    ('sentry-mcp', 'developer-workflow-code-management'),
    ('brave-search-mcp', 'research-competitive-intelligence'),
    ('tavily-mcp', 'research-competitive-intelligence'),
    ('perplexity-mcp', 'research-competitive-intelligence'),
    ('browserbase-mcp', 'qa-testing-automation'),
    ('puppeteer-mcp', 'qa-testing-automation'),
    ('storybook-mcp', 'design-to-code-workflow'),
    ('tailwindcss-mcp', 'design-to-code-workflow'),
    ('obsidian-mcp', 'knowledge-management'),
    ('confluence-mcp', 'knowledge-management'),
    ('terraform-mcp', 'it-devops-platform-operations'),
    ('kubernetes-mcp', 'it-devops-platform-operations'),
    ('cloudflare-mcp', 'it-devops-platform-operations'),
    ('supabase-mcp', 'data-analysis-reporting'),
    ('neon-mcp', 'data-analysis-reporting'),
    ('zendesk-mcp', 'customer-support-automation'),
    ('intercom-mcp', 'customer-support-automation'),
    ('hubspot-mcp', 'sales-research-outreach'),
    ('apollo-mcp', 'sales-research-outreach'),
    ('salesforce-mcp', 'sales-research-outreach'),
    ('wordpress-mcp', 'content-creation-publishing'),
    ('sanity-mcp', 'content-creation-publishing'),
    ('ghost-mcp', 'content-creation-publishing'),
    ('google-ads-mcp', 'marketing-intelligence-campaign-management'),
    ('mailchimp-mcp', 'marketing-intelligence-campaign-management'),
    ('semrush-mcp', 'marketing-intelligence-campaign-management'),
    ('stripe-mcp', 'finance-accounting-automation'),
    ('quickbooks-mcp', 'finance-accounting-automation'),
    ('plaid-mcp', 'finance-accounting-automation'),
    ('docusign-mcp', 'legal-research-document-management'),
    ('legalforce-mcp', 'legal-research-document-management'),
    ('courtlistener-mcp', 'legal-research-document-management'),
    ('greenhouse-mcp', 'hr-recruiting-automation'),
    ('lever-mcp', 'hr-recruiting-automation'),
    ('bamboohr-mcp', 'hr-recruiting-automation'),
    ('shopify-mcp', 'ecommerce-operations'),
    ('woocommerce-mcp', 'ecommerce-operations'),
    ('amazon-seller-mcp', 'ecommerce-operations'),
    ('snyk-mcp', 'security-operations'),
    ('sonarqube-mcp', 'security-operations'),
    ('trivy-mcp', 'security-operations'),
    ('google-calendar-mcp', 'executive-assistant-productivity'),
    ('slack-mcp', 'executive-assistant-productivity'),
    ('gmail-mcp', 'executive-assistant-productivity'),
    -- Original 10 skills
    ('context7', 'developer-workflow-code-management'),
    ('github-mcp-server', 'developer-workflow-code-management'),
    ('playwright-mcp', 'qa-testing-automation'),
    ('firecrawl-mcp', 'research-competitive-intelligence'),
    ('exa-mcp-server', 'research-competitive-intelligence'),
    ('aws-mcp', 'it-devops-platform-operations'),
    ('figma-context-mcp', 'design-to-code-workflow'),
    ('atlassian-mcp', 'customer-support-automation'),
    ('notion-mcp-server', 'knowledge-management'),
    ('genai-toolbox', 'data-analysis-reporting')
) AS t(skill_slug, workflow_slug)
JOIN skills s ON s.slug = t.skill_slug
JOIN workflows w ON w.slug = t.workflow_slug
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────
-- MAP SKILLS TO VERTICALS
-- ─────────────────────────────────────────────
INSERT INTO skill_verticals (skill_id, vertical_id)
SELECT s.id, v.id FROM (
  VALUES
    ('gitlab-mcp'::text, 'engineering-development'::text),
    ('linear-mcp', 'engineering-development'),
    ('sentry-mcp', 'engineering-development'),
    ('brave-search-mcp', 'general-business-operations'),
    ('tavily-mcp', 'general-business-operations'),
    ('perplexity-mcp', 'general-business-operations'),
    ('browserbase-mcp', 'engineering-development'),
    ('puppeteer-mcp', 'engineering-development'),
    ('storybook-mcp', 'engineering-development'),
    ('tailwindcss-mcp', 'engineering-development'),
    ('obsidian-mcp', 'general-business-operations'),
    ('confluence-mcp', 'general-business-operations'),
    ('terraform-mcp', 'engineering-development'),
    ('kubernetes-mcp', 'engineering-development'),
    ('cloudflare-mcp', 'engineering-development'),
    ('supabase-mcp', 'engineering-development'),
    ('neon-mcp', 'engineering-development'),
    ('zendesk-mcp', 'customer-support'),
    ('intercom-mcp', 'customer-support'),
    ('hubspot-mcp', 'sales-revenue'),
    ('apollo-mcp', 'sales-revenue'),
    ('salesforce-mcp', 'sales-revenue'),
    ('wordpress-mcp', 'marketing-content'),
    ('sanity-mcp', 'marketing-content'),
    ('ghost-mcp', 'marketing-content'),
    ('google-ads-mcp', 'marketing-content'),
    ('mailchimp-mcp', 'marketing-content'),
    ('semrush-mcp', 'marketing-content'),
    ('stripe-mcp', 'finance-accounting'),
    ('quickbooks-mcp', 'finance-accounting'),
    ('plaid-mcp', 'finance-accounting'),
    ('docusign-mcp', 'legal-compliance'),
    ('legalforce-mcp', 'legal-compliance'),
    ('courtlistener-mcp', 'legal-compliance'),
    ('greenhouse-mcp', 'hr-recruiting'),
    ('lever-mcp', 'hr-recruiting'),
    ('bamboohr-mcp', 'hr-recruiting'),
    ('shopify-mcp', 'ecommerce-retail'),
    ('woocommerce-mcp', 'ecommerce-retail'),
    ('amazon-seller-mcp', 'ecommerce-retail'),
    ('snyk-mcp', 'cybersecurity'),
    ('sonarqube-mcp', 'cybersecurity'),
    ('trivy-mcp', 'cybersecurity'),
    ('google-calendar-mcp', 'general-business-operations'),
    ('slack-mcp', 'general-business-operations'),
    ('gmail-mcp', 'general-business-operations'),
    -- Original 10
    ('context7', 'engineering-development'),
    ('github-mcp-server', 'engineering-development'),
    ('playwright-mcp', 'engineering-development'),
    ('firecrawl-mcp', 'general-business-operations'),
    ('exa-mcp-server', 'general-business-operations'),
    ('aws-mcp', 'engineering-development'),
    ('figma-context-mcp', 'engineering-development'),
    ('atlassian-mcp', 'customer-support'),
    ('notion-mcp-server', 'general-business-operations'),
    ('genai-toolbox', 'engineering-development')
) AS t(skill_slug, vertical_slug)
JOIN skills s ON s.slug = t.skill_slug
JOIN verticals v ON v.slug = t.vertical_slug
ON CONFLICT DO NOTHING;
