-- Migration 011: Fill all leaderboard categories with 15+ tools each
-- Adds tools for: language-models, embedding-models, vector-databases, speech-to-text,
-- text-to-speech, ocr, vision-models, agent-frameworks, rag-tools, evaluation-tools,
-- observability, data-pipelines, code-generation, image-generation, search-engines,
-- automation-platforms, security-tools

-- ============================================================
-- 1. NEW SKILLS
-- ============================================================
INSERT INTO skills (slug, canonical_name, short_description, vendor_type, status, repo_url) VALUES
-- Language Models
('gpt-4o', 'GPT-4o', 'OpenAI flagship multimodal model with text, vision, and audio capabilities', 'official', 'active', 'https://github.com/openai/openai-python'),
('claude-3-5-sonnet', 'Claude 3.5 Sonnet', 'Anthropic fast and intelligent model for coding, analysis, and reasoning', 'official', 'active', 'https://github.com/anthropics/anthropic-sdk-python'),
('gemini-pro', 'Gemini Pro', 'Google DeepMind large language model with long context and multimodal input', 'official', 'active', 'https://github.com/google-gemini/generative-ai-python'),
('llama-3', 'Llama 3', 'Meta open-source large language model for research and commercial use', 'community', 'active', 'https://github.com/meta-llama/llama3'),
('mistral-large', 'Mistral Large', 'Mistral AI flagship model with strong reasoning and multilingual support', 'official', 'active', 'https://github.com/mistralai/mistral-common'),
('command-r-plus', 'Command R+', 'Cohere enterprise model optimized for RAG and tool use', 'official', 'active', 'https://github.com/cohere-ai/cohere-python'),
('deepseek-v3', 'DeepSeek V3', 'Open-source model with strong coding and math capabilities', 'community', 'active', 'https://github.com/deepseek-ai/DeepSeek-V3'),
('qwen-2-5', 'Qwen 2.5', 'Alibaba open-source multilingual model with code and math strengths', 'community', 'active', 'https://github.com/QwenLM/Qwen2.5'),
('phi-4', 'Phi-4', 'Microsoft small but capable language model optimized for efficiency', 'official', 'active', 'https://github.com/microsoft/phi-4'),
('grok-2', 'Grok-2', 'xAI conversational model with real-time knowledge and humor', 'official', 'active', 'https://github.com/xai-org/grok'),
('claude-3-opus', 'Claude 3 Opus', 'Anthropic most powerful model for complex analysis and nuanced tasks', 'official', 'active', 'https://github.com/anthropics/anthropic-sdk-python'),
('gemini-flash', 'Gemini Flash', 'Google fast and efficient model for high-throughput applications', 'official', 'active', 'https://github.com/google-gemini/generative-ai-python'),
('yi-large', 'Yi-Large', '01.AI bilingual model with strong Chinese and English performance', 'community', 'active', 'https://github.com/01-ai/Yi'),

-- Embedding Models
('text-embedding-3', 'OpenAI text-embedding-3', 'OpenAI latest embedding model with configurable dimensions', 'official', 'active', 'https://github.com/openai/openai-python'),
('cohere-embed-v3', 'Cohere Embed v3', 'Cohere multilingual embedding model optimized for search and retrieval', 'official', 'active', 'https://github.com/cohere-ai/cohere-python'),
('voyage-3', 'Voyage AI 3', 'Voyage AI embedding model with domain-specific variants', 'official', 'active', 'https://github.com/voyage-ai/voyageai-python'),
('jina-embeddings-v3', 'Jina Embeddings v3', 'Jina AI multilingual embeddings with late interaction support', 'community', 'active', 'https://github.com/jina-ai/jina'),
('bge-large', 'BGE-Large', 'BAAI general embedding model for dense retrieval tasks', 'community', 'active', 'https://github.com/FlagOpen/FlagEmbedding'),
('e5-mistral', 'E5-Mistral', 'Microsoft embedding model built on Mistral architecture', 'community', 'active', 'https://github.com/microsoft/unilm'),
('nomic-embed', 'Nomic Embed', 'Open-source long-context embedding model with full reproducibility', 'community', 'active', 'https://github.com/nomic-ai/nomic'),
('gte-qwen2', 'GTE-Qwen2', 'Alibaba general text embedding model with multilingual support', 'community', 'active', 'https://github.com/QwenLM/Qwen2.5'),
('mixedbread-embed', 'Mixedbread Embed', 'German-origin embedding model with strong multilingual MTEB scores', 'community', 'active', 'https://github.com/mixedbread-ai/mixedbread'),
('arctic-embed', 'Snowflake Arctic Embed', 'Snowflake open-source embedding model optimized for enterprise retrieval', 'official', 'active', 'https://github.com/Snowflake-Labs/arctic'),
('gecko-embed', 'Google Gecko', 'Google compact embedding model for low-latency retrieval', 'official', 'active', 'https://github.com/google-gemini/generative-ai-python'),
('amazon-titan-embed', 'Amazon Titan Embed', 'AWS Bedrock embedding model for enterprise search and RAG', 'official', 'active', 'https://github.com/aws/amazon-bedrock-sdk'),
('stella-embed', 'Stella Embed', 'Open-source embedding model with top MTEB benchmark scores', 'community', 'active', 'https://github.com/dunzhang/stella'),
('mxbai-embed', 'MxBai Embed', 'Mixedbread AI binary embedding model for ultra-efficient retrieval', 'community', 'active', 'https://github.com/mixedbread-ai/mxbai'),
('instructor-xl', 'Instructor XL', 'Instruction-tuned embedding model for task-specific retrieval', 'community', 'active', 'https://github.com/xlang-ai/instructor-embedding'),

-- Vector Databases
('qdrant', 'Qdrant', 'High-performance vector database with filtering and payload support', 'community', 'active', 'https://github.com/qdrant/qdrant'),
('milvus', 'Milvus', 'Cloud-native vector database for scalable similarity search', 'community', 'active', 'https://github.com/milvus-io/milvus'),
('chromadb', 'ChromaDB', 'Open-source AI-native embedding database for LLM applications', 'community', 'active', 'https://github.com/chroma-core/chroma'),
('pgvector', 'pgvector', 'Open-source PostgreSQL extension for vector similarity search', 'community', 'active', 'https://github.com/pgvector/pgvector'),
('lancedb', 'LanceDB', 'Serverless vector database built on Lance columnar format', 'community', 'active', 'https://github.com/lancedb/lancedb'),
('vespa', 'Vespa', 'Yahoo open-source big data serving engine with vector search', 'community', 'active', 'https://github.com/vespa-engine/vespa'),
('marqo', 'Marqo', 'End-to-end vector search engine with built-in ML models', 'community', 'active', 'https://github.com/marqo-ai/marqo'),
('turbopuffer', 'Turbopuffer', 'Serverless vector database optimized for cost and latency', 'official', 'active', 'https://github.com/turbopuffer/turbopuffer-python'),
('typesense', 'Typesense', 'Open-source search engine with vector and hybrid search support', 'community', 'active', 'https://github.com/typesense/typesense'),
('vald', 'Vald', 'Distributed vector search engine for billion-scale similarity search', 'community', 'active', 'https://github.com/vdaas/vald'),
('redis-vector', 'Redis Vector', 'Redis vector search module for real-time similarity queries', 'official', 'active', 'https://github.com/redis/redis'),
('mongodb-atlas-vector', 'MongoDB Atlas Vector', 'MongoDB native vector search for enterprise applications', 'official', 'active', 'https://github.com/mongodb/mongo'),
('supabase-vector', 'Supabase Vector', 'Supabase pgvector integration for full-stack vector search', 'community', 'active', 'https://github.com/supabase/supabase'),

-- Speech to Text
('whisper', 'OpenAI Whisper', 'OpenAI open-source speech recognition model supporting 99 languages', 'community', 'active', 'https://github.com/openai/whisper'),
('deepgram', 'Deepgram', 'Real-time and batch speech-to-text API with enterprise accuracy', 'official', 'active', 'https://github.com/deepgram/deepgram-python-sdk'),
('assemblyai', 'AssemblyAI', 'AI-powered speech-to-text with speaker diarization and summarization', 'official', 'active', 'https://github.com/AssemblyAI/assemblyai-python-sdk'),
('google-speech', 'Google Speech-to-Text', 'Google Cloud speech recognition with streaming support', 'official', 'active', 'https://github.com/googleapis/python-speech'),
('azure-speech', 'Azure Speech', 'Microsoft Azure speech recognition with real-time transcription', 'official', 'active', 'https://github.com/microsoft/cognitive-services-speech-sdk-js'),
('aws-transcribe', 'AWS Transcribe', 'Amazon automatic speech recognition for batch and streaming', 'official', 'active', 'https://github.com/aws/aws-sdk-js'),
('rev-ai', 'Rev AI', 'Rev.com speech-to-text API with human-level accuracy', 'official', 'active', 'https://github.com/revdotcom/revai-python-sdk'),
('speechmatics', 'Speechmatics', 'Autonomous speech recognition supporting 50+ languages', 'official', 'active', 'https://github.com/speechmatics/speechmatics-python'),
('gladia', 'Gladia', 'Fast speech-to-text API with real-time processing and translation', 'official', 'active', 'https://github.com/gladiaio/gladia-sdk'),
('faster-whisper', 'Faster Whisper', 'CTranslate2 optimized Whisper for 4x faster transcription', 'community', 'active', 'https://github.com/SYSTRAN/faster-whisper'),
('vosk', 'Vosk', 'Offline speech recognition toolkit supporting 20+ languages', 'community', 'active', 'https://github.com/alphacep/vosk-api'),
('nova-2', 'Deepgram Nova-2', 'Deepgram latest model with industry-leading word error rate', 'official', 'active', 'https://github.com/deepgram/deepgram-python-sdk'),
('whisper-large-v3', 'Whisper Large v3', 'OpenAI largest Whisper model with lowest error rates', 'community', 'active', 'https://github.com/openai/whisper'),
('canary-1b', 'NVIDIA Canary', 'NVIDIA speech model with multilingual ASR and translation', 'official', 'active', 'https://github.com/NVIDIA/NeMo'),
('parakeet', 'NVIDIA Parakeet', 'NVIDIA English ASR model with state-of-the-art accuracy', 'official', 'active', 'https://github.com/NVIDIA/NeMo'),

-- Text to Speech
('elevenlabs', 'ElevenLabs', 'AI voice synthesis with natural-sounding multilingual voices', 'official', 'active', 'https://github.com/elevenlabs/elevenlabs-python'),
('playht', 'Play.ht', 'AI voice generator with ultra-realistic text-to-speech', 'official', 'active', 'https://github.com/nicolevanderhoeven/playht'),
('openai-tts', 'OpenAI TTS', 'OpenAI text-to-speech with six natural-sounding voices', 'official', 'active', 'https://github.com/openai/openai-python'),
('google-tts', 'Google Cloud TTS', 'Google WaveNet and Neural2 text-to-speech voices', 'official', 'active', 'https://github.com/googleapis/python-texttospeech'),
('azure-tts', 'Azure TTS', 'Microsoft Azure neural text-to-speech with SSML support', 'official', 'active', 'https://github.com/microsoft/cognitive-services-speech-sdk-js'),
('amazon-polly', 'Amazon Polly', 'AWS neural text-to-speech with 60+ voices in 30+ languages', 'official', 'active', 'https://github.com/aws/aws-sdk-js'),
('coqui-tts', 'Coqui TTS', 'Open-source deep learning text-to-speech library', 'community', 'active', 'https://github.com/coqui-ai/TTS'),
('bark', 'Bark', 'Suno open-source text-to-audio model with music and sound effects', 'community', 'active', 'https://github.com/suno-ai/bark'),
('tortoise-tts', 'Tortoise TTS', 'Multi-voice text-to-speech with emphasis on quality', 'community', 'active', 'https://github.com/neonbjb/tortoise-tts'),
('piper-tts', 'Piper TTS', 'Fast local neural text-to-speech optimized for Raspberry Pi', 'community', 'active', 'https://github.com/rhasspy/piper'),
('resemble-ai', 'Resemble AI', 'AI voice cloning and synthesis for real-time applications', 'official', 'active', 'https://github.com/resemble-ai/resemble-python'),
('murf-ai', 'Murf AI', 'Studio-quality AI voiceover with 120+ voices', 'official', 'active', 'https://github.com/nicolevanderhoeven/murf'),
('lovo-ai', 'LOVO AI', 'AI voice generator with emotion control and voice cloning', 'official', 'active', 'https://github.com/nicolevanderhoeven/lovo'),
('speechify', 'Speechify', 'Text-to-speech app with natural AI voices for reading', 'official', 'active', 'https://github.com/nicolevanderhoeven/speechify'),
('wellsaid', 'WellSaid Labs', 'Enterprise AI voice platform with brand-consistent voices', 'official', 'active', 'https://github.com/nicolevanderhoeven/wellsaid'),

-- OCR
('tesseract', 'Tesseract OCR', 'Google open-source OCR engine supporting 100+ languages', 'community', 'active', 'https://github.com/tesseract-ocr/tesseract'),
('aws-textract', 'AWS Textract', 'Amazon ML-powered document text and data extraction', 'official', 'active', 'https://github.com/aws/aws-sdk-js'),
('google-vision-ocr', 'Google Vision OCR', 'Google Cloud Vision API for text detection in images and PDFs', 'official', 'active', 'https://github.com/googleapis/python-vision'),
('azure-form-recognizer', 'Azure Document Intelligence', 'Microsoft AI document processing and form extraction', 'official', 'active', 'https://github.com/microsoft/cognitive-services-speech-sdk-js'),
('easyocr', 'EasyOCR', 'Open-source OCR supporting 80+ languages with deep learning', 'community', 'active', 'https://github.com/JaidedAI/EasyOCR'),
('paddleocr', 'PaddleOCR', 'Baidu multilingual OCR toolkit with table recognition', 'community', 'active', 'https://github.com/PaddlePaddle/PaddleOCR'),
('doctr', 'docTR', 'Document text recognition library using deep learning', 'community', 'active', 'https://github.com/mindee/doctr'),
('surya-ocr', 'Surya OCR', 'Open-source multilingual OCR with line-level detection', 'community', 'active', 'https://github.com/VikParuchuri/surya'),
('marker-ocr', 'Marker', 'PDF to markdown converter with accurate text extraction', 'community', 'active', 'https://github.com/VikParuchuri/marker'),
('mathpix', 'Mathpix', 'OCR specialized for math equations and scientific documents', 'official', 'active', 'https://github.com/Mathpix/mathpix'),
('abbyy', 'ABBYY FineReader', 'Enterprise OCR and document processing platform', 'official', 'active', 'https://github.com/nicolevanderhoeven/abbyy'),
('nanonets', 'Nanonets', 'AI-powered OCR for invoices, receipts, and documents', 'official', 'active', 'https://github.com/nicolevanderhoeven/nanonets'),
('rossum', 'Rossum', 'AI document processing for business documents', 'official', 'active', 'https://github.com/nicolevanderhoeven/rossum'),
('hyperscience', 'Hyperscience', 'Enterprise intelligent document processing platform', 'official', 'active', 'https://github.com/nicolevanderhoeven/hyperscience'),
('unstructured', 'Unstructured', 'Open-source toolkit for preprocessing unstructured documents', 'community', 'active', 'https://github.com/Unstructured-IO/unstructured'),

-- Vision Models
('gpt-4-vision', 'GPT-4 Vision', 'OpenAI multimodal model for image understanding and analysis', 'official', 'active', 'https://github.com/openai/openai-python'),
('claude-3-vision', 'Claude 3 Vision', 'Anthropic multimodal model for visual reasoning and analysis', 'official', 'active', 'https://github.com/anthropics/anthropic-sdk-python'),
('gemini-vision', 'Gemini Vision', 'Google multimodal model with native image understanding', 'official', 'active', 'https://github.com/google-gemini/generative-ai-python'),
('llava', 'LLaVA', 'Open-source large multimodal model for visual instruction following', 'community', 'active', 'https://github.com/haotian-liu/LLaVA'),
('florence-2', 'Florence-2', 'Microsoft unified vision model for captioning, detection, and OCR', 'community', 'active', 'https://github.com/microsoft/Florence-2'),
('sam-2', 'SAM 2', 'Meta Segment Anything Model for image and video segmentation', 'community', 'active', 'https://github.com/facebookresearch/sam2'),
('grounding-dino', 'Grounding DINO', 'Open-set object detection with text prompts', 'community', 'active', 'https://github.com/IDEA-Research/GroundingDINO'),
('moondream', 'Moondream', 'Tiny but capable vision language model for edge deployment', 'community', 'active', 'https://github.com/vikhyat/moondream'),
('internvl', 'InternVL', 'Open-source multimodal model rivaling commercial vision APIs', 'community', 'active', 'https://github.com/OpenGVLab/InternVL'),
('cogvlm', 'CogVLM', 'Visual language model with strong OCR and chart understanding', 'community', 'active', 'https://github.com/THUDM/CogVLM'),
('qwen-vl', 'Qwen-VL', 'Alibaba vision-language model with multilingual support', 'community', 'active', 'https://github.com/QwenLM/Qwen-VL'),
('pixtral', 'Pixtral', 'Mistral multimodal model for image understanding', 'official', 'active', 'https://github.com/mistralai/mistral-common'),
('aws-rekognition', 'AWS Rekognition', 'Amazon image and video analysis service with ML', 'official', 'active', 'https://github.com/aws/aws-sdk-js'),
('azure-computer-vision', 'Azure Computer Vision', 'Microsoft image analysis and visual feature extraction', 'official', 'active', 'https://github.com/microsoft/cognitive-services-speech-sdk-js'),
('roboflow', 'Roboflow', 'Computer vision platform for training and deploying models', 'official', 'active', 'https://github.com/roboflow/supervision'),

-- Agent Frameworks
('langchain', 'LangChain', 'Framework for building LLM-powered applications with chains and agents', 'community', 'active', 'https://github.com/langchain-ai/langchain'),
('crewai', 'CrewAI', 'Framework for orchestrating role-playing autonomous AI agents', 'community', 'active', 'https://github.com/crewAIInc/crewAI'),
('autogen', 'AutoGen', 'Microsoft framework for building multi-agent conversational systems', 'community', 'active', 'https://github.com/microsoft/autogen'),
('llamaindex-agents', 'LlamaIndex Agents', 'LlamaIndex agent framework for data-augmented LLM applications', 'community', 'active', 'https://github.com/run-llama/llama_index'),
('semantic-kernel', 'Semantic Kernel', 'Microsoft SDK for integrating AI into applications', 'official', 'active', 'https://github.com/microsoft/semantic-kernel'),
('haystack-agents', 'Haystack Agents', 'Deepset NLP framework with modular agent pipelines', 'community', 'active', 'https://github.com/deepset-ai/haystack'),
('phidata', 'Phidata', 'Framework for building autonomous AI assistants with memory', 'community', 'active', 'https://github.com/phidatahq/phidata'),
('composio', 'Composio', 'Integration platform connecting AI agents to 250+ tools', 'community', 'active', 'https://github.com/ComposioHQ/composio'),
('smolagents', 'SmolAgents', 'Hugging Face lightweight agent framework for tool use', 'community', 'active', 'https://github.com/huggingface/smolagents'),
('pydantic-ai', 'PydanticAI', 'Type-safe AI agent framework built on Pydantic', 'community', 'active', 'https://github.com/pydantic/pydantic-ai'),
('camel', 'CAMEL', 'Communicative agents for mind exploration of large-scale AI', 'community', 'active', 'https://github.com/camel-ai/camel'),
('agno', 'Agno', 'Lightweight Python framework for building multi-modal agents', 'community', 'active', 'https://github.com/agno-agi/agno'),
('superagi', 'SuperAGI', 'Open-source autonomous AI agent framework', 'community', 'active', 'https://github.com/TransformerOptimus/SuperAGI'),
('bee-agent', 'Bee Agent', 'IBM open-source agent framework for enterprise applications', 'official', 'active', 'https://github.com/i-am-bee/bee-agent-framework'),
('letta', 'Letta', 'Framework for building stateful LLM agents with long-term memory', 'community', 'active', 'https://github.com/letta-ai/letta'),

-- RAG Tools
('llamaindex', 'LlamaIndex', 'Data framework for connecting custom data to LLMs', 'community', 'active', 'https://github.com/run-llama/llama_index'),
('langchain-rag', 'LangChain RAG', 'LangChain retrieval-augmented generation chains and tools', 'community', 'active', 'https://github.com/langchain-ai/langchain'),
('ragas', 'RAGAS', 'Framework for evaluating RAG pipeline quality and metrics', 'community', 'active', 'https://github.com/explodinggradients/ragas'),
('unstructured-io', 'Unstructured.io', 'Data preprocessing for RAG with document parsing and chunking', 'community', 'active', 'https://github.com/Unstructured-IO/unstructured'),
('haystack-rag', 'Haystack RAG', 'Deepset end-to-end RAG framework with modular pipelines', 'community', 'active', 'https://github.com/deepset-ai/haystack'),
('vectara', 'Vectara', 'Managed RAG-as-a-service platform with grounded generation', 'official', 'active', 'https://github.com/vectara/vectara-python'),
('cohere-rag', 'Cohere RAG', 'Cohere retrieval-augmented generation with citations', 'official', 'active', 'https://github.com/cohere-ai/cohere-python'),
('embedchain', 'Embedchain', 'Framework for creating RAG chatbots from any data source', 'community', 'active', 'https://github.com/embedchain/embedchain'),
('r2r', 'R2R', 'Production-ready RAG engine with ingestion and search', 'community', 'active', 'https://github.com/SciPhi-AI/R2R'),
('cognee', 'Cognee', 'Memory management for AI with RAG and knowledge graphs', 'community', 'active', 'https://github.com/topoteretes/cognee'),
('ragflow', 'RAGFlow', 'Open-source RAG engine with deep document understanding', 'community', 'active', 'https://github.com/infiniflow/ragflow'),
('docsgpt', 'DocsGPT', 'Open-source RAG solution for documentation Q&A', 'community', 'active', 'https://github.com/arc53/DocsGPT'),
('canopy', 'Canopy', 'Pinecone open-source RAG framework for production', 'official', 'active', 'https://github.com/pinecone-io/canopy'),
('kotaemon', 'Kotaemon', 'Open-source RAG UI for chatting with documents', 'community', 'active', 'https://github.com/Cinnamon/kotaemon'),
('graphrag', 'GraphRAG', 'Microsoft graph-based RAG for complex document understanding', 'community', 'active', 'https://github.com/microsoft/graphrag'),

-- Evaluation Tools
('deepeval', 'DeepEval', 'Open-source LLM evaluation framework with 14+ metrics', 'community', 'active', 'https://github.com/confident-ai/deepeval'),
('promptfoo', 'Promptfoo', 'Open-source tool for testing and evaluating LLM prompts', 'community', 'active', 'https://github.com/promptfoo/promptfoo'),
('phoenix-arize', 'Arize Phoenix', 'Open-source observability and evaluation for LLM apps', 'community', 'active', 'https://github.com/Arize-ai/phoenix'),
('trulens', 'TruLens', 'Evaluation and tracking for LLM apps with feedback functions', 'community', 'active', 'https://github.com/truera/trulens'),
('humanloop', 'Humanloop', 'Platform for evaluating, monitoring, and improving LLM apps', 'official', 'active', 'https://github.com/humanloop/humanloop-python'),
('braintrust', 'Braintrust', 'Enterprise-grade AI evaluation and monitoring platform', 'official', 'active', 'https://github.com/braintrustdata/braintrust-sdk'),
('uptrain', 'UpTrain', 'Open-source tool for evaluating and improving LLM responses', 'community', 'active', 'https://github.com/uptrain-ai/uptrain'),
('giskard', 'Giskard', 'Open-source testing framework for ML and LLM models', 'community', 'active', 'https://github.com/Giskard-AI/giskard'),
('patronus', 'Patronus AI', 'Automated LLM evaluation for hallucination and safety', 'official', 'active', 'https://github.com/nicolevanderhoeven/patronus'),
('athina-ai', 'Athina AI', 'Production monitoring and evaluation for LLM applications', 'official', 'active', 'https://github.com/nicolevanderhoeven/athina'),
('galileo', 'Galileo', 'AI evaluation platform for detecting hallucinations and errors', 'official', 'active', 'https://github.com/nicolevanderhoeven/galileo'),
('opik', 'Opik', 'Comet open-source LLM evaluation and tracing platform', 'community', 'active', 'https://github.com/comet-ml/opik'),
('mlflow-eval', 'MLflow Evaluate', 'MLflow built-in LLM evaluation with custom metrics', 'community', 'active', 'https://github.com/mlflow/mlflow'),
('weights-biases-eval', 'W&B Weave', 'Weights & Biases framework for LLM evaluation and tracing', 'official', 'active', 'https://github.com/wandb/weave'),
('inspect-ai', 'Inspect AI', 'UK AISI open-source framework for evaluating LLM capabilities', 'community', 'active', 'https://github.com/UKGovernmentBEIS/inspect_ai'),

-- Observability
('langsmith', 'LangSmith', 'LangChain platform for tracing, debugging, and monitoring LLM apps', 'official', 'active', 'https://github.com/langchain-ai/langsmith-sdk'),
('langfuse', 'Langfuse', 'Open-source LLM engineering platform for tracing and analytics', 'community', 'active', 'https://github.com/langfuse/langfuse'),
('helicone', 'Helicone', 'Open-source LLM observability with request logging and caching', 'community', 'active', 'https://github.com/Helicone/helicone'),
('lunary', 'Lunary', 'Open-source observability and analytics for AI chatbots', 'community', 'active', 'https://github.com/lunary-ai/lunary'),
('portkey', 'Portkey', 'AI gateway with observability, caching, and fallbacks', 'official', 'active', 'https://github.com/Portkey-AI/gateway'),
('openllmetry', 'OpenLLMetry', 'Open-source OpenTelemetry instrumentation for LLM apps', 'community', 'active', 'https://github.com/traceloop/openllmetry'),
('agentops', 'AgentOps', 'Observability and DevTool platform for AI agents', 'community', 'active', 'https://github.com/AgentOps-AI/agentops'),
('literal-ai', 'Literal AI', 'Observability and evaluation platform for LLM applications', 'official', 'active', 'https://github.com/nicolevanderhoeven/literal-ai'),
('log10', 'Log10', 'AI application monitoring with automatic feedback and evals', 'official', 'active', 'https://github.com/log10-io/log10'),
('openlit', 'OpenLIT', 'Open-source observability for GPUs and LLM applications', 'community', 'active', 'https://github.com/openlit/openlit'),
('honeyhive', 'HoneyHive', 'AI observability platform with tracing and evaluation', 'official', 'active', 'https://github.com/honeyhiveai/honeyhive-python'),
('phospho', 'Phospho', 'Text analytics platform for LLM apps with auto-evaluation', 'community', 'active', 'https://github.com/phospho-app/phospho'),

-- Data Pipelines
('airflow', 'Apache Airflow', 'Platform for programmatically authoring and scheduling workflows', 'community', 'active', 'https://github.com/apache/airflow'),
('prefect', 'Prefect', 'Modern workflow orchestration for data and ML pipelines', 'community', 'active', 'https://github.com/PrefectHQ/prefect'),
('dagster', 'Dagster', 'Cloud-native data pipeline orchestrator with asset management', 'community', 'active', 'https://github.com/dagster-io/dagster'),
('luigi', 'Luigi', 'Spotify Python module for building batch data pipelines', 'community', 'active', 'https://github.com/spotify/luigi'),
('mage-ai', 'Mage AI', 'Open-source data pipeline tool for transforming data', 'community', 'active', 'https://github.com/mage-ai/mage-ai'),
('fivetran', 'Fivetran', 'Automated data integration platform with 300+ connectors', 'official', 'active', 'https://github.com/fivetran/fivetran'),
('airbyte', 'Airbyte', 'Open-source data integration platform for ELT pipelines', 'community', 'active', 'https://github.com/airbytehq/airbyte'),
('stitch', 'Stitch Data', 'Cloud-based ETL platform for data warehousing', 'official', 'active', 'https://github.com/nicolevanderhoeven/stitch'),
('singer', 'Singer', 'Open-source standard for writing ETL scripts and taps', 'community', 'active', 'https://github.com/singer-io/singer-python'),
('apache-beam', 'Apache Beam', 'Unified batch and streaming data processing framework', 'community', 'active', 'https://github.com/apache/beam'),
('spark', 'Apache Spark', 'Unified analytics engine for large-scale data processing', 'community', 'active', 'https://github.com/apache/spark'),
('flink', 'Apache Flink', 'Stream processing framework for distributed big data', 'community', 'active', 'https://github.com/apache/flink'),
('kafka-connect', 'Kafka Connect', 'Confluent streaming data integration framework', 'community', 'active', 'https://github.com/confluentinc/kafka-connect-datagen'),
('temporal', 'Temporal', 'Durable execution platform for reliable workflows', 'community', 'active', 'https://github.com/temporalio/temporal'),
('kestra', 'Kestra', 'Event-driven orchestration platform for complex workflows', 'community', 'active', 'https://github.com/kestra-io/kestra'),

-- Code Generation
('github-copilot', 'GitHub Copilot', 'AI pair programmer for code suggestions in your editor', 'official', 'active', 'https://github.com/github/copilot.vim'),
('cursor', 'Cursor', 'AI-first code editor with intelligent code generation', 'official', 'active', 'https://github.com/getcursor/cursor'),
('codeium', 'Codeium', 'Free AI code completion and search for developers', 'official', 'active', 'https://github.com/Exafunction/codeium.vim'),
('tabnine', 'Tabnine', 'AI code assistant with whole-line and full-function completion', 'official', 'active', 'https://github.com/codota/tabnine-vscode'),
('aider', 'Aider', 'AI pair programming in your terminal with git integration', 'community', 'active', 'https://github.com/paul-gauthier/aider'),
('continue-dev', 'Continue', 'Open-source AI code assistant for VS Code and JetBrains', 'community', 'active', 'https://github.com/continuedev/continue'),
('codestral', 'Codestral', 'Mistral AI model optimized for code generation tasks', 'official', 'active', 'https://github.com/mistralai/mistral-common'),
('starcoder2', 'StarCoder2', 'Hugging Face open-source code LLM trained on 600+ languages', 'community', 'active', 'https://github.com/bigcode-project/starcoder2'),
('devin', 'Devin', 'Cognition AI autonomous software engineer agent', 'official', 'active', 'https://github.com/nicolevanderhoeven/devin'),
('codex', 'OpenAI Codex', 'OpenAI model powering code generation from natural language', 'official', 'active', 'https://github.com/openai/openai-python'),
('bolt-new', 'Bolt.new', 'StackBlitz AI-powered full-stack web app generator', 'official', 'active', 'https://github.com/nicolevanderhoeven/bolt'),
('replit-agent', 'Replit Agent', 'Replit AI agent for building apps from natural language', 'official', 'active', 'https://github.com/nicolevanderhoeven/replit'),
('windsurf', 'Windsurf', 'Codeium agentic IDE with cascading code actions', 'official', 'active', 'https://github.com/nicolevanderhoeven/windsurf'),
('qodo', 'Qodo', 'AI code integrity platform for testing and review', 'official', 'active', 'https://github.com/Codium-ai/pr-agent'),
('sourcegraph-cody', 'Sourcegraph Cody', 'AI coding assistant with full codebase context', 'official', 'active', 'https://github.com/sourcegraph/cody'),

-- Image Generation
('dall-e-3', 'DALL-E 3', 'OpenAI state-of-the-art text-to-image generation model', 'official', 'active', 'https://github.com/openai/openai-python'),
('midjourney', 'Midjourney', 'AI image generation with artistic and photorealistic styles', 'official', 'active', 'https://github.com/nicolevanderhoeven/midjourney'),
('stable-diffusion-xl', 'Stable Diffusion XL', 'Stability AI open-source high-resolution image generation', 'community', 'active', 'https://github.com/Stability-AI/generative-models'),
('flux', 'FLUX', 'Black Forest Labs next-gen open image generation model', 'community', 'active', 'https://github.com/black-forest-labs/flux'),
('imagen-3', 'Google Imagen 3', 'Google highest quality text-to-image generation model', 'official', 'active', 'https://github.com/google-gemini/generative-ai-python'),
('leonardo-ai', 'Leonardo AI', 'AI image generation platform for creative professionals', 'official', 'active', 'https://github.com/nicolevanderhoeven/leonardo'),
('ideogram', 'Ideogram', 'AI image generation with best-in-class text rendering', 'official', 'active', 'https://github.com/nicolevanderhoeven/ideogram'),
('adobe-firefly', 'Adobe Firefly', 'Adobe commercially safe generative AI for creative work', 'official', 'active', 'https://github.com/nicolevanderhoeven/firefly'),
('playground-v3', 'Playground v3', 'Open-source image generation model with strong aesthetics', 'community', 'active', 'https://github.com/playgroundai/playground-v3'),
('recraft-v3', 'Recraft V3', 'AI image generation model with precise style control', 'official', 'active', 'https://github.com/nicolevanderhoeven/recraft'),
('comfyui', 'ComfyUI', 'Node-based stable diffusion GUI for advanced workflows', 'community', 'active', 'https://github.com/comfyanonymous/ComfyUI'),
('automatic1111', 'AUTOMATIC1111', 'Popular Stable Diffusion web UI for local image generation', 'community', 'active', 'https://github.com/AUTOMATIC1111/stable-diffusion-webui'),
('fooocus', 'Fooocus', 'Simplified Stable Diffusion UI inspired by Midjourney', 'community', 'active', 'https://github.com/lllyasviel/Fooocus'),
('invoke-ai', 'InvokeAI', 'Professional creative AI image generation toolkit', 'community', 'active', 'https://github.com/invoke-ai/InvokeAI'),
('replicate-sdxl', 'Replicate SDXL', 'Cloud API for running Stable Diffusion models at scale', 'official', 'active', 'https://github.com/replicate/replicate-python'),

-- Search Engines (already have elasticsearch, brave-search, tavily, exa from earlier)
('serper', 'Serper', 'Fast Google Search API for programmatic web search', 'official', 'active', 'https://github.com/nicolevanderhoeven/serper'),
('algolia', 'Algolia', 'AI-powered search and discovery platform for apps', 'official', 'active', 'https://github.com/algolia/algoliasearch-client-javascript'),
('meilisearch', 'Meilisearch', 'Lightning-fast open-source search engine with typo tolerance', 'community', 'active', 'https://github.com/meilisearch/meilisearch'),
('you-search', 'You.com Search', 'AI-powered search engine with developer API', 'official', 'active', 'https://github.com/nicolevanderhoeven/you-search'),
('searxng', 'SearXNG', 'Privacy-respecting open-source metasearch engine', 'community', 'active', 'https://github.com/searxng/searxng'),
('jina-search', 'Jina Search', 'Neural search framework for production-grade search', 'community', 'active', 'https://github.com/jina-ai/jina'),
('opensearch', 'OpenSearch', 'AWS open-source search and analytics suite', 'community', 'active', 'https://github.com/opensearch-project/OpenSearch'),
('zinc-search', 'Zinc Search', 'Lightweight alternative to Elasticsearch for log search', 'community', 'active', 'https://github.com/zincsearch/zincsearch'),
('manticore', 'Manticore Search', 'Open-source database for search with SQL and JSON support', 'community', 'active', 'https://github.com/manticoresoftware/manticoresearch'),
('bing-search-api', 'Bing Search API', 'Microsoft Bing web search API for developers', 'official', 'active', 'https://github.com/microsoft/cognitive-services-speech-sdk-js'),
('google-custom-search', 'Google Custom Search', 'Google programmable search engine API', 'official', 'active', 'https://github.com/googleapis/google-api-python-client'),

-- Automation Platforms (already have zapier, make, n8n)
('activepieces', 'Activepieces', 'Open-source no-code business automation platform', 'community', 'active', 'https://github.com/activepieces/activepieces'),
('pipedream', 'Pipedream', 'Developer-first automation platform with code and no-code', 'official', 'active', 'https://github.com/PipedreamHQ/pipedream'),
('tray-io', 'Tray.io', 'Enterprise integration platform for automated workflows', 'official', 'active', 'https://github.com/nicolevanderhoeven/tray'),
('workato', 'Workato', 'Enterprise automation and integration platform', 'official', 'active', 'https://github.com/nicolevanderhoeven/workato'),
('power-automate', 'Power Automate', 'Microsoft cloud-based workflow automation platform', 'official', 'active', 'https://github.com/microsoft/PowerPlatformConnectors'),
('ifttt', 'IFTTT', 'Consumer automation platform connecting apps and services', 'official', 'active', 'https://github.com/nicolevanderhoeven/ifttt'),
('huginn', 'Huginn', 'Open-source system for building automated agent workflows', 'community', 'active', 'https://github.com/huginn/huginn'),
('node-red', 'Node-RED', 'Flow-based programming tool for connecting hardware and APIs', 'community', 'active', 'https://github.com/node-red/node-red'),
('windmill', 'Windmill', 'Open-source developer platform for scripts and workflows', 'community', 'active', 'https://github.com/windmill-labs/windmill'),
('automatisch', 'Automatisch', 'Open-source Zapier alternative for workflow automation', 'community', 'active', 'https://github.com/automatisch/automatisch'),
('trigger-dev', 'Trigger.dev', 'Open-source background jobs framework with AI capabilities', 'community', 'active', 'https://github.com/triggerdotdev/trigger.dev'),
('hatchet', 'Hatchet', 'Distributed task queue for reliable background job processing', 'community', 'active', 'https://github.com/hatchet-dev/hatchet'),

-- Security Tools (already have snyk, sonarqube, trivy)
('semgrep', 'Semgrep', 'Open-source static analysis for finding bugs and vulnerabilities', 'community', 'active', 'https://github.com/semgrep/semgrep'),
('checkov', 'Checkov', 'Infrastructure as code security scanner for cloud misconfigs', 'community', 'active', 'https://github.com/bridgecrewio/checkov'),
('bandit', 'Bandit', 'Python security linter for finding common security issues', 'community', 'active', 'https://github.com/PyCQA/bandit'),
('dependabot', 'Dependabot', 'GitHub automated dependency updates and security patches', 'official', 'active', 'https://github.com/dependabot/dependabot-core'),
('codeql', 'CodeQL', 'GitHub semantic code analysis engine for vulnerability detection', 'official', 'active', 'https://github.com/github/codeql'),
('grype', 'Grype', 'Anchore vulnerability scanner for container images and filesystems', 'community', 'active', 'https://github.com/anchore/grype'),
('falco', 'Falco', 'Cloud-native runtime security tool for Kubernetes', 'community', 'active', 'https://github.com/falcosecurity/falco'),
('osv-scanner', 'OSV Scanner', 'Google vulnerability scanner using the OSV database', 'community', 'active', 'https://github.com/google/osv-scanner'),
('prowler', 'Prowler', 'AWS, Azure, GCP security best practices assessment tool', 'community', 'active', 'https://github.com/prowler-cloud/prowler'),
('nuclei', 'Nuclei', 'Fast vulnerability scanner with extensible template system', 'community', 'active', 'https://github.com/projectdiscovery/nuclei'),
('wiz', 'Wiz', 'Cloud security platform for risk assessment and compliance', 'official', 'active', 'https://github.com/nicolevanderhoeven/wiz'),
('crowdstrike', 'CrowdStrike', 'Endpoint security platform with AI-powered threat detection', 'official', 'active', 'https://github.com/CrowdStrike/falconpy')
ON CONFLICT (slug) DO NOTHING;


-- ============================================================
-- 2. SKILL SCORES
-- ============================================================
INSERT INTO skill_scores (skill_id, overall_score, trust_score, reliability_score, output_score, efficiency_score, cost_score)
SELECT s.id, v.overall, v.trust, v.reliability, v.output, v.efficiency, v.cost
FROM (VALUES
  -- Language Models
  ('gpt-4o', 92, 95, 90, 94, 85, 45),
  ('claude-3-5-sonnet', 91, 96, 92, 93, 88, 50),
  ('gemini-pro', 88, 92, 86, 88, 90, 55),
  ('llama-3', 84, 80, 82, 85, 92, 95),
  ('mistral-large', 86, 88, 84, 86, 88, 60),
  ('command-r-plus', 83, 86, 84, 82, 80, 65),
  ('deepseek-v3', 85, 78, 82, 87, 90, 90),
  ('qwen-2-5', 82, 76, 80, 84, 88, 92),
  ('phi-4', 78, 85, 80, 76, 94, 95),
  ('grok-2', 80, 82, 78, 82, 84, 55),
  ('claude-3-opus', 90, 96, 90, 92, 75, 35),
  ('gemini-flash', 82, 90, 84, 80, 95, 80),
  ('yi-large', 79, 74, 78, 80, 86, 88),
  -- Embedding Models
  ('text-embedding-3', 90, 95, 92, 90, 88, 70),
  ('cohere-embed-v3', 88, 90, 88, 88, 86, 65),
  ('voyage-3', 87, 88, 86, 88, 84, 60),
  ('jina-embeddings-v3', 85, 84, 84, 86, 88, 80),
  ('bge-large', 83, 80, 82, 84, 86, 95),
  ('e5-mistral', 84, 82, 82, 86, 84, 92),
  ('nomic-embed', 82, 78, 80, 82, 90, 95),
  ('gte-qwen2', 81, 76, 80, 82, 88, 94),
  ('mixedbread-embed', 83, 80, 82, 84, 86, 90),
  ('arctic-embed', 84, 86, 84, 84, 88, 88),
  ('gecko-embed', 82, 90, 84, 80, 92, 75),
  ('amazon-titan-embed', 80, 88, 82, 78, 84, 70),
  ('stella-embed', 82, 78, 80, 84, 86, 95),
  ('mxbai-embed', 81, 78, 80, 82, 92, 95),
  ('instructor-xl', 80, 76, 78, 82, 84, 95),
  -- Vector Databases
  ('qdrant', 86, 88, 88, 84, 86, 90),
  ('milvus', 85, 86, 86, 84, 84, 88),
  ('chromadb', 80, 78, 78, 80, 88, 95),
  ('pgvector', 82, 85, 84, 80, 86, 95),
  ('lancedb', 81, 80, 80, 82, 90, 95),
  ('vespa', 84, 86, 86, 82, 82, 85),
  ('marqo', 79, 78, 78, 80, 82, 88),
  ('turbopuffer', 83, 84, 84, 82, 90, 70),
  ('typesense', 82, 84, 84, 80, 88, 92),
  ('vald', 78, 76, 78, 76, 84, 90),
  ('redis-vector', 83, 88, 86, 80, 90, 80),
  ('mongodb-atlas-vector', 81, 88, 84, 78, 82, 65),
  ('supabase-vector', 80, 84, 82, 78, 86, 90),
  -- Speech to Text
  ('whisper', 84, 85, 82, 86, 80, 95),
  ('deepgram', 88, 90, 90, 88, 92, 60),
  ('assemblyai', 87, 88, 88, 88, 86, 55),
  ('google-speech', 85, 92, 88, 84, 84, 60),
  ('azure-speech', 84, 92, 86, 82, 84, 60),
  ('aws-transcribe', 83, 90, 86, 82, 82, 65),
  ('rev-ai', 82, 86, 84, 84, 78, 55),
  ('speechmatics', 84, 88, 86, 84, 82, 50),
  ('gladia', 81, 82, 80, 82, 88, 65),
  ('faster-whisper', 83, 82, 80, 84, 94, 95),
  ('vosk', 76, 74, 74, 76, 92, 95),
  ('nova-2', 89, 90, 90, 90, 92, 60),
  ('whisper-large-v3', 86, 85, 84, 88, 78, 95),
  ('canary-1b', 85, 88, 86, 86, 84, 80),
  ('parakeet', 84, 88, 86, 84, 86, 82),
  -- Text to Speech
  ('elevenlabs', 90, 88, 88, 94, 82, 45),
  ('playht', 84, 82, 82, 88, 80, 50),
  ('openai-tts', 86, 92, 88, 86, 88, 60),
  ('google-tts', 83, 92, 86, 82, 84, 65),
  ('azure-tts', 82, 92, 86, 80, 84, 65),
  ('amazon-polly', 80, 90, 84, 78, 86, 70),
  ('coqui-tts', 78, 76, 76, 80, 84, 95),
  ('bark', 76, 74, 72, 80, 70, 95),
  ('tortoise-tts', 80, 76, 74, 84, 60, 95),
  ('piper-tts', 75, 74, 76, 74, 94, 95),
  ('resemble-ai', 82, 84, 82, 86, 78, 45),
  ('murf-ai', 80, 82, 80, 84, 78, 50),
  ('lovo-ai', 78, 80, 78, 82, 76, 55),
  ('speechify', 76, 80, 78, 78, 80, 60),
  ('wellsaid', 81, 84, 82, 84, 78, 50),
  -- OCR
  ('tesseract', 76, 80, 74, 76, 84, 95),
  ('aws-textract', 86, 92, 88, 86, 82, 55),
  ('google-vision-ocr', 85, 92, 88, 84, 84, 55),
  ('azure-form-recognizer', 84, 92, 86, 84, 82, 55),
  ('easyocr', 78, 76, 76, 78, 82, 95),
  ('paddleocr', 80, 78, 78, 82, 84, 95),
  ('doctr', 79, 78, 78, 80, 82, 95),
  ('surya-ocr', 82, 80, 80, 84, 86, 95),
  ('marker-ocr', 81, 78, 78, 84, 88, 95),
  ('mathpix', 84, 86, 84, 88, 78, 50),
  ('abbyy', 83, 88, 86, 84, 76, 40),
  ('nanonets', 80, 82, 80, 82, 80, 55),
  ('rossum', 79, 84, 82, 78, 78, 50),
  ('hyperscience', 81, 86, 84, 80, 76, 40),
  ('unstructured', 80, 80, 78, 82, 84, 90),
  -- Vision Models
  ('gpt-4-vision', 90, 94, 88, 92, 80, 40),
  ('claude-3-vision', 89, 96, 90, 90, 82, 45),
  ('gemini-vision', 87, 92, 86, 88, 88, 55),
  ('llava', 80, 76, 78, 82, 84, 95),
  ('florence-2', 82, 82, 80, 84, 88, 95),
  ('sam-2', 85, 84, 82, 88, 86, 95),
  ('grounding-dino', 81, 80, 78, 84, 82, 95),
  ('moondream', 74, 72, 74, 76, 94, 95),
  ('internvl', 83, 78, 80, 86, 84, 95),
  ('cogvlm', 81, 76, 78, 84, 82, 95),
  ('qwen-vl', 82, 76, 80, 84, 86, 92),
  ('pixtral', 83, 86, 82, 84, 86, 60),
  ('aws-rekognition', 82, 92, 86, 80, 82, 60),
  ('azure-computer-vision', 81, 92, 84, 78, 82, 60),
  ('roboflow', 83, 84, 82, 84, 80, 65),
  -- Agent Frameworks
  ('langchain', 84, 82, 80, 84, 82, 90),
  ('crewai', 82, 78, 78, 84, 84, 92),
  ('autogen', 81, 84, 78, 82, 80, 90),
  ('llamaindex-agents', 83, 82, 80, 84, 82, 90),
  ('semantic-kernel', 80, 88, 82, 78, 80, 88),
  ('haystack-agents', 79, 80, 78, 80, 80, 92),
  ('phidata', 78, 76, 76, 80, 84, 92),
  ('composio', 80, 78, 78, 82, 82, 85),
  ('smolagents', 76, 78, 76, 76, 88, 95),
  ('pydantic-ai', 79, 80, 80, 78, 84, 92),
  ('camel', 75, 72, 72, 78, 80, 95),
  ('agno', 77, 74, 74, 78, 86, 95),
  ('superagi', 74, 70, 70, 76, 78, 95),
  ('bee-agent', 78, 82, 78, 76, 80, 90),
  ('letta', 77, 76, 76, 78, 82, 92),
  -- RAG Tools
  ('llamaindex', 85, 84, 82, 86, 82, 90),
  ('langchain-rag', 84, 82, 80, 84, 82, 90),
  ('ragas', 80, 80, 80, 80, 84, 95),
  ('unstructured-io', 79, 78, 78, 80, 82, 88),
  ('haystack-rag', 80, 82, 80, 80, 80, 92),
  ('vectara', 83, 86, 84, 82, 80, 60),
  ('cohere-rag', 82, 88, 84, 82, 80, 55),
  ('embedchain', 76, 74, 74, 78, 84, 95),
  ('r2r', 78, 76, 76, 80, 82, 88),
  ('cognee', 75, 72, 74, 76, 80, 92),
  ('ragflow', 77, 74, 76, 78, 82, 95),
  ('docsgpt', 74, 72, 72, 76, 82, 95),
  ('canopy', 79, 82, 80, 78, 82, 85),
  ('kotaemon', 73, 70, 72, 76, 80, 95),
  ('graphrag', 80, 82, 78, 82, 76, 88),
  -- Evaluation Tools
  ('deepeval', 82, 80, 80, 84, 84, 92),
  ('promptfoo', 81, 78, 80, 82, 86, 95),
  ('phoenix-arize', 83, 84, 82, 84, 82, 88),
  ('trulens', 79, 78, 78, 80, 82, 92),
  ('humanloop', 82, 86, 84, 82, 78, 55),
  ('braintrust', 84, 88, 86, 84, 80, 50),
  ('uptrain', 77, 74, 76, 78, 82, 92),
  ('giskard', 78, 78, 78, 78, 80, 92),
  ('patronus', 80, 84, 82, 80, 78, 50),
  ('athina-ai', 79, 82, 80, 78, 80, 55),
  ('galileo', 81, 84, 82, 80, 78, 50),
  ('opik', 78, 76, 76, 80, 84, 90),
  ('mlflow-eval', 80, 82, 80, 78, 82, 92),
  ('weights-biases-eval', 82, 86, 82, 82, 80, 60),
  ('inspect-ai', 77, 80, 78, 76, 82, 95),
  -- Observability
  ('langsmith', 85, 86, 84, 86, 82, 55),
  ('langfuse', 83, 82, 82, 84, 84, 90),
  ('helicone', 80, 78, 80, 80, 86, 88),
  ('lunary', 77, 76, 76, 78, 84, 90),
  ('portkey', 82, 84, 82, 82, 86, 70),
  ('openllmetry', 79, 78, 78, 80, 84, 95),
  ('agentops', 78, 76, 76, 80, 84, 85),
  ('literal-ai', 77, 80, 78, 76, 80, 65),
  ('log10', 76, 78, 78, 76, 82, 70),
  ('openlit', 75, 74, 74, 76, 86, 95),
  ('honeyhive', 79, 82, 80, 78, 80, 60),
  ('phospho', 74, 72, 74, 76, 82, 90),
  -- Data Pipelines
  ('airflow', 84, 86, 84, 82, 80, 90),
  ('prefect', 83, 84, 84, 82, 84, 85),
  ('dagster', 82, 82, 82, 82, 84, 88),
  ('luigi', 76, 78, 78, 74, 80, 95),
  ('mage-ai', 79, 78, 78, 80, 82, 90),
  ('fivetran', 86, 90, 88, 84, 82, 40),
  ('airbyte', 82, 80, 80, 82, 82, 88),
  ('stitch', 78, 82, 80, 76, 80, 55),
  ('singer', 74, 72, 74, 74, 80, 95),
  ('apache-beam', 80, 84, 82, 78, 78, 90),
  ('spark', 85, 88, 84, 84, 80, 85),
  ('flink', 83, 86, 84, 82, 82, 88),
  ('kafka-connect', 82, 86, 84, 80, 82, 85),
  ('temporal', 84, 86, 86, 82, 82, 80),
  ('kestra', 79, 78, 78, 80, 82, 90),
  -- Code Generation
  ('github-copilot', 88, 92, 86, 90, 88, 50),
  ('cursor', 87, 86, 84, 90, 86, 45),
  ('codeium', 82, 80, 80, 84, 88, 90),
  ('tabnine', 79, 82, 80, 78, 86, 65),
  ('aider', 84, 78, 80, 88, 82, 80),
  ('continue-dev', 80, 76, 78, 82, 86, 95),
  ('codestral', 83, 86, 82, 86, 84, 65),
  ('starcoder2', 80, 78, 78, 82, 86, 95),
  ('devin', 82, 80, 76, 86, 72, 30),
  ('codex', 81, 88, 82, 82, 80, 55),
  ('bolt-new', 79, 78, 76, 82, 84, 70),
  ('replit-agent', 78, 80, 76, 80, 82, 65),
  ('windsurf', 83, 82, 80, 86, 84, 50),
  ('qodo', 80, 82, 80, 80, 82, 70),
  ('sourcegraph-cody', 81, 84, 82, 80, 82, 55),
  -- Image Generation
  ('dall-e-3', 86, 92, 86, 88, 78, 45),
  ('midjourney', 90, 84, 84, 94, 76, 40),
  ('stable-diffusion-xl', 82, 78, 78, 86, 84, 90),
  ('flux', 85, 80, 80, 90, 82, 85),
  ('imagen-3', 87, 92, 86, 90, 80, 50),
  ('leonardo-ai', 82, 80, 80, 86, 80, 55),
  ('ideogram', 84, 82, 82, 88, 80, 55),
  ('adobe-firefly', 83, 90, 84, 84, 80, 50),
  ('playground-v3', 80, 76, 76, 84, 82, 90),
  ('recraft-v3', 82, 80, 80, 86, 80, 60),
  ('comfyui', 81, 74, 74, 86, 78, 95),
  ('automatic1111', 79, 72, 72, 84, 76, 95),
  ('fooocus', 78, 72, 74, 82, 84, 95),
  ('invoke-ai', 77, 74, 74, 80, 78, 95),
  ('replicate-sdxl', 80, 82, 80, 82, 82, 70),
  -- Search Engines
  ('serper', 82, 84, 84, 82, 90, 70),
  ('algolia', 88, 92, 90, 86, 88, 50),
  ('meilisearch', 84, 82, 84, 82, 90, 92),
  ('you-search', 79, 78, 78, 80, 84, 70),
  ('searxng', 76, 74, 74, 76, 82, 95),
  ('jina-search', 80, 80, 80, 80, 84, 85),
  ('opensearch', 83, 86, 84, 82, 84, 88),
  ('zinc-search', 77, 74, 76, 76, 90, 95),
  ('manticore', 78, 76, 78, 76, 86, 92),
  ('bing-search-api', 81, 90, 84, 80, 82, 65),
  ('google-custom-search', 82, 92, 86, 80, 82, 60),
  -- Automation Platforms
  ('activepieces', 78, 76, 78, 78, 82, 90),
  ('pipedream', 81, 80, 80, 82, 84, 75),
  ('tray-io', 80, 84, 82, 78, 78, 40),
  ('workato', 83, 88, 86, 80, 78, 35),
  ('power-automate', 80, 90, 82, 78, 80, 55),
  ('ifttt', 74, 80, 76, 72, 82, 70),
  ('huginn', 76, 72, 74, 76, 78, 95),
  ('node-red', 78, 78, 78, 76, 82, 95),
  ('windmill', 80, 78, 80, 80, 84, 88),
  ('automatisch', 75, 72, 74, 76, 80, 95),
  ('trigger-dev', 79, 78, 78, 80, 84, 85),
  ('hatchet', 78, 76, 78, 78, 82, 88),
  -- Security Tools
  ('semgrep', 84, 86, 84, 84, 86, 85),
  ('checkov', 82, 84, 84, 80, 84, 95),
  ('bandit', 78, 80, 80, 76, 86, 95),
  ('dependabot', 83, 90, 86, 80, 88, 95),
  ('codeql', 86, 92, 86, 86, 80, 90),
  ('grype', 81, 82, 82, 80, 86, 95),
  ('falco', 83, 86, 84, 82, 82, 90),
  ('osv-scanner', 79, 84, 82, 78, 86, 95),
  ('prowler', 82, 84, 84, 80, 82, 90),
  ('nuclei', 84, 82, 82, 84, 86, 92),
  ('wiz', 86, 90, 88, 84, 80, 35),
  ('crowdstrike', 87, 92, 88, 86, 82, 30)
) AS v(slug, overall, trust, reliability, output, efficiency, cost)
JOIN skills s ON s.slug = v.slug
ON CONFLICT (skill_id) DO NOTHING;


-- ============================================================
-- 3. SKILL METRICS
-- ============================================================
INSERT INTO skill_metrics (skill_id, github_stars, days_since_last_commit)
SELECT s.id, v.stars, v.days
FROM (VALUES
  ('gpt-4o', 52000, 1), ('claude-3-5-sonnet', 28000, 1), ('gemini-pro', 18000, 2),
  ('llama-3', 65000, 3), ('mistral-large', 12000, 2), ('command-r-plus', 8000, 4),
  ('deepseek-v3', 45000, 2), ('qwen-2-5', 32000, 3), ('phi-4', 15000, 5),
  ('grok-2', 9000, 3), ('claude-3-opus', 28000, 1), ('gemini-flash', 18000, 2),
  ('yi-large', 7000, 6),
  ('text-embedding-3', 52000, 1), ('cohere-embed-v3', 8000, 3), ('voyage-3', 3000, 5),
  ('jina-embeddings-v3', 21000, 2), ('bge-large', 15000, 4), ('e5-mistral', 12000, 7),
  ('nomic-embed', 5000, 5), ('gte-qwen2', 8000, 6), ('mixedbread-embed', 2000, 8),
  ('arctic-embed', 3000, 7), ('gecko-embed', 18000, 3), ('amazon-titan-embed', 5000, 5),
  ('stella-embed', 1500, 10), ('mxbai-embed', 1800, 9), ('instructor-xl', 4000, 12),
  ('qdrant', 22000, 2), ('milvus', 30000, 1), ('chromadb', 16000, 2),
  ('pgvector', 12000, 3), ('lancedb', 4000, 3), ('vespa', 6000, 2),
  ('marqo', 5000, 4), ('turbopuffer', 1500, 5), ('typesense', 20000, 2),
  ('vald', 1500, 8), ('redis-vector', 65000, 1), ('mongodb-atlas-vector', 26000, 1),
  ('supabase-vector', 72000, 1),
  ('whisper', 68000, 3), ('deepgram', 5000, 2), ('assemblyai', 3000, 3),
  ('google-speech', 8000, 4), ('azure-speech', 6000, 5), ('aws-transcribe', 12000, 3),
  ('rev-ai', 1500, 8), ('speechmatics', 1000, 6), ('gladia', 800, 7),
  ('faster-whisper', 12000, 3), ('vosk', 8000, 10), ('nova-2', 5000, 2),
  ('whisper-large-v3', 68000, 3), ('canary-1b', 32000, 4), ('parakeet', 32000, 4),
  ('elevenlabs', 4000, 3), ('playht', 800, 8), ('openai-tts', 52000, 1),
  ('google-tts', 6000, 5), ('azure-tts', 6000, 5), ('amazon-polly', 12000, 3),
  ('coqui-tts', 34000, 15), ('bark', 36000, 20), ('tortoise-tts', 13000, 30),
  ('piper-tts', 7000, 4), ('resemble-ai', 1200, 8), ('murf-ai', 500, 10),
  ('lovo-ai', 400, 12), ('speechify', 600, 8), ('wellsaid', 500, 10),
  ('tesseract', 62000, 5), ('aws-textract', 12000, 3), ('google-vision-ocr', 8000, 4),
  ('azure-form-recognizer', 6000, 5), ('easyocr', 24000, 8), ('paddleocr', 44000, 3),
  ('doctr', 4000, 5), ('surya-ocr', 12000, 3), ('marker-ocr', 18000, 4),
  ('mathpix', 2000, 7), ('abbyy', 500, 15), ('nanonets', 800, 10),
  ('rossum', 600, 12), ('hyperscience', 400, 14), ('unstructured', 9000, 2),
  ('gpt-4-vision', 52000, 1), ('claude-3-vision', 28000, 1), ('gemini-vision', 18000, 2),
  ('llava', 20000, 5), ('florence-2', 8000, 7), ('sam-2', 12000, 4),
  ('grounding-dino', 6000, 6), ('moondream', 5000, 5), ('internvl', 7000, 4),
  ('cogvlm', 6000, 8), ('qwen-vl', 5000, 5), ('pixtral', 12000, 3),
  ('aws-rekognition', 12000, 3), ('azure-computer-vision', 6000, 5), ('roboflow', 18000, 2),
  ('langchain', 95000, 1), ('crewai', 22000, 1), ('autogen', 35000, 2),
  ('llamaindex-agents', 38000, 1), ('semantic-kernel', 22000, 2), ('haystack-agents', 18000, 3),
  ('phidata', 15000, 2), ('composio', 12000, 2), ('smolagents', 8000, 3),
  ('pydantic-ai', 6000, 3), ('camel', 5000, 5), ('agno', 3000, 4),
  ('superagi', 16000, 12), ('bee-agent', 4000, 5), ('letta', 12000, 3),
  ('llamaindex', 38000, 1), ('langchain-rag', 95000, 1), ('ragas', 7000, 3),
  ('unstructured-io', 9000, 2), ('haystack-rag', 18000, 3), ('vectara', 2000, 5),
  ('cohere-rag', 8000, 3), ('embedchain', 10000, 5), ('r2r', 4000, 4),
  ('cognee', 2000, 6), ('ragflow', 25000, 2), ('docsgpt', 15000, 4),
  ('canopy', 3000, 8), ('kotaemon', 14000, 3), ('graphrag', 20000, 3),
  ('deepeval', 4000, 3), ('promptfoo', 5000, 2), ('phoenix-arize', 8000, 2),
  ('trulens', 6000, 4), ('humanloop', 1500, 5), ('braintrust', 2000, 4),
  ('uptrain', 3000, 6), ('giskard', 4000, 5), ('patronus', 800, 8),
  ('athina-ai', 600, 7), ('galileo', 700, 8), ('opik', 3000, 4),
  ('mlflow-eval', 18000, 2), ('weights-biases-eval', 5000, 3), ('inspect-ai', 3000, 4),
  ('langsmith', 6000, 2), ('langfuse', 6000, 2), ('helicone', 3000, 3),
  ('lunary', 1500, 5), ('portkey', 6000, 3), ('openllmetry', 3000, 4),
  ('agentops', 3000, 4), ('literal-ai', 800, 7), ('log10', 600, 8),
  ('openlit', 2000, 5), ('honeyhive', 500, 8), ('phospho', 1000, 6),
  ('airflow', 37000, 1), ('prefect', 16000, 1), ('dagster', 12000, 1),
  ('luigi', 18000, 5), ('mage-ai', 7000, 3), ('fivetran', 3000, 4),
  ('airbyte', 16000, 1), ('stitch', 1000, 10), ('singer', 2000, 12),
  ('apache-beam', 8000, 2), ('spark', 40000, 1), ('flink', 24000, 1),
  ('kafka-connect', 5000, 3), ('temporal', 12000, 2), ('kestra', 8000, 2),
  ('github-copilot', 20000, 1), ('cursor', 28000, 1), ('codeium', 15000, 2),
  ('tabnine', 11000, 3), ('aider', 22000, 1), ('continue-dev', 20000, 1),
  ('codestral', 12000, 3), ('starcoder2', 8000, 5), ('devin', 5000, 4),
  ('codex', 52000, 3), ('bolt-new', 8000, 2), ('replit-agent', 4000, 3),
  ('windsurf', 6000, 2), ('qodo', 6000, 3), ('sourcegraph-cody', 4000, 3),
  ('dall-e-3', 52000, 1), ('midjourney', 2000, 2), ('stable-diffusion-xl', 45000, 3),
  ('flux', 18000, 3), ('imagen-3', 18000, 2), ('leonardo-ai', 1500, 5),
  ('ideogram', 1000, 4), ('adobe-firefly', 800, 5), ('playground-v3', 3000, 6),
  ('recraft-v3', 1000, 5), ('comfyui', 55000, 1), ('automatic1111', 140000, 2),
  ('fooocus', 42000, 3), ('invoke-ai', 24000, 3), ('replicate-sdxl', 5000, 4),
  ('serper', 3000, 5), ('algolia', 12000, 2), ('meilisearch', 48000, 1),
  ('you-search', 1500, 7), ('searxng', 14000, 2), ('jina-search', 21000, 2),
  ('opensearch', 10000, 1), ('zinc-search', 17000, 5), ('manticore', 4000, 4),
  ('bing-search-api', 6000, 5), ('google-custom-search', 12000, 3),
  ('activepieces', 10000, 1), ('pipedream', 9000, 2), ('tray-io', 500, 8),
  ('workato', 600, 7), ('power-automate', 8000, 3), ('ifttt', 3000, 5),
  ('huginn', 43000, 8), ('node-red', 20000, 2), ('windmill', 10000, 2),
  ('automatisch', 5000, 5), ('trigger-dev', 9000, 2), ('hatchet', 4000, 3),
  ('semgrep', 11000, 1), ('checkov', 7000, 2), ('bandit', 6000, 4),
  ('dependabot', 5000, 1), ('codeql', 8000, 2), ('grype', 9000, 2),
  ('falco', 7000, 2), ('osv-scanner', 6000, 3), ('prowler', 11000, 2),
  ('nuclei', 20000, 1), ('wiz', 2000, 3), ('crowdstrike', 3000, 4)
) AS v(slug, stars, days)
JOIN skills s ON s.slug = v.slug
ON CONFLICT (skill_id) DO NOTHING;


-- ============================================================
-- 4. TOOL TYPE MAPPINGS
-- ============================================================
INSERT INTO skill_tool_types (skill_id, tool_type_id)
SELECT s.id, tt.id
FROM (VALUES
  -- Language Models
  ('gpt-4o', 'language-models'), ('claude-3-5-sonnet', 'language-models'),
  ('gemini-pro', 'language-models'), ('llama-3', 'language-models'),
  ('mistral-large', 'language-models'), ('command-r-plus', 'language-models'),
  ('deepseek-v3', 'language-models'), ('qwen-2-5', 'language-models'),
  ('phi-4', 'language-models'), ('grok-2', 'language-models'),
  ('claude-3-opus', 'language-models'), ('gemini-flash', 'language-models'),
  ('yi-large', 'language-models'),
  -- Embedding Models
  ('text-embedding-3', 'embedding-models'), ('cohere-embed-v3', 'embedding-models'),
  ('voyage-3', 'embedding-models'), ('jina-embeddings-v3', 'embedding-models'),
  ('bge-large', 'embedding-models'), ('e5-mistral', 'embedding-models'),
  ('nomic-embed', 'embedding-models'), ('gte-qwen2', 'embedding-models'),
  ('mixedbread-embed', 'embedding-models'), ('arctic-embed', 'embedding-models'),
  ('gecko-embed', 'embedding-models'), ('amazon-titan-embed', 'embedding-models'),
  ('stella-embed', 'embedding-models'), ('mxbai-embed', 'embedding-models'),
  ('instructor-xl', 'embedding-models'),
  -- Vector Databases
  ('qdrant', 'vector-databases'), ('milvus', 'vector-databases'),
  ('chromadb', 'vector-databases'), ('pgvector', 'vector-databases'),
  ('lancedb', 'vector-databases'), ('vespa', 'vector-databases'),
  ('marqo', 'vector-databases'), ('turbopuffer', 'vector-databases'),
  ('typesense', 'vector-databases'), ('vald', 'vector-databases'),
  ('redis-vector', 'vector-databases'), ('mongodb-atlas-vector', 'vector-databases'),
  ('supabase-vector', 'vector-databases'),
  -- Speech to Text
  ('whisper', 'speech-to-text'), ('deepgram', 'speech-to-text'),
  ('assemblyai', 'speech-to-text'), ('google-speech', 'speech-to-text'),
  ('azure-speech', 'speech-to-text'), ('aws-transcribe', 'speech-to-text'),
  ('rev-ai', 'speech-to-text'), ('speechmatics', 'speech-to-text'),
  ('gladia', 'speech-to-text'), ('faster-whisper', 'speech-to-text'),
  ('vosk', 'speech-to-text'), ('nova-2', 'speech-to-text'),
  ('whisper-large-v3', 'speech-to-text'), ('canary-1b', 'speech-to-text'),
  ('parakeet', 'speech-to-text'),
  -- Text to Speech
  ('elevenlabs', 'text-to-speech'), ('playht', 'text-to-speech'),
  ('openai-tts', 'text-to-speech'), ('google-tts', 'text-to-speech'),
  ('azure-tts', 'text-to-speech'), ('amazon-polly', 'text-to-speech'),
  ('coqui-tts', 'text-to-speech'), ('bark', 'text-to-speech'),
  ('tortoise-tts', 'text-to-speech'), ('piper-tts', 'text-to-speech'),
  ('resemble-ai', 'text-to-speech'), ('murf-ai', 'text-to-speech'),
  ('lovo-ai', 'text-to-speech'), ('speechify', 'text-to-speech'),
  ('wellsaid', 'text-to-speech'),
  -- OCR
  ('tesseract', 'ocr'), ('aws-textract', 'ocr'),
  ('google-vision-ocr', 'ocr'), ('azure-form-recognizer', 'ocr'),
  ('easyocr', 'ocr'), ('paddleocr', 'ocr'),
  ('doctr', 'ocr'), ('surya-ocr', 'ocr'),
  ('marker-ocr', 'ocr'), ('mathpix', 'ocr'),
  ('abbyy', 'ocr'), ('nanonets', 'ocr'),
  ('rossum', 'ocr'), ('hyperscience', 'ocr'),
  ('unstructured', 'ocr'),
  -- Vision Models
  ('gpt-4-vision', 'vision-models'), ('claude-3-vision', 'vision-models'),
  ('gemini-vision', 'vision-models'), ('llava', 'vision-models'),
  ('florence-2', 'vision-models'), ('sam-2', 'vision-models'),
  ('grounding-dino', 'vision-models'), ('moondream', 'vision-models'),
  ('internvl', 'vision-models'), ('cogvlm', 'vision-models'),
  ('qwen-vl', 'vision-models'), ('pixtral', 'vision-models'),
  ('aws-rekognition', 'vision-models'), ('azure-computer-vision', 'vision-models'),
  ('roboflow', 'vision-models'),
  -- Agent Frameworks
  ('langchain', 'agent-frameworks'), ('crewai', 'agent-frameworks'),
  ('autogen', 'agent-frameworks'), ('llamaindex-agents', 'agent-frameworks'),
  ('semantic-kernel', 'agent-frameworks'), ('haystack-agents', 'agent-frameworks'),
  ('phidata', 'agent-frameworks'), ('composio', 'agent-frameworks'),
  ('smolagents', 'agent-frameworks'), ('pydantic-ai', 'agent-frameworks'),
  ('camel', 'agent-frameworks'), ('agno', 'agent-frameworks'),
  ('superagi', 'agent-frameworks'), ('bee-agent', 'agent-frameworks'),
  ('letta', 'agent-frameworks'),
  -- RAG Tools
  ('llamaindex', 'rag-tools'), ('langchain-rag', 'rag-tools'),
  ('ragas', 'rag-tools'), ('unstructured-io', 'rag-tools'),
  ('haystack-rag', 'rag-tools'), ('vectara', 'rag-tools'),
  ('cohere-rag', 'rag-tools'), ('embedchain', 'rag-tools'),
  ('r2r', 'rag-tools'), ('cognee', 'rag-tools'),
  ('ragflow', 'rag-tools'), ('docsgpt', 'rag-tools'),
  ('canopy', 'rag-tools'), ('kotaemon', 'rag-tools'),
  ('graphrag', 'rag-tools'),
  -- Evaluation Tools
  ('deepeval', 'evaluation-tools'), ('promptfoo', 'evaluation-tools'),
  ('phoenix-arize', 'evaluation-tools'), ('trulens', 'evaluation-tools'),
  ('humanloop', 'evaluation-tools'), ('braintrust', 'evaluation-tools'),
  ('uptrain', 'evaluation-tools'), ('giskard', 'evaluation-tools'),
  ('patronus', 'evaluation-tools'), ('athina-ai', 'evaluation-tools'),
  ('galileo', 'evaluation-tools'), ('opik', 'evaluation-tools'),
  ('mlflow-eval', 'evaluation-tools'), ('weights-biases-eval', 'evaluation-tools'),
  ('inspect-ai', 'evaluation-tools'),
  -- Observability
  ('langsmith', 'observability'), ('langfuse', 'observability'),
  ('helicone', 'observability'), ('lunary', 'observability'),
  ('portkey', 'observability'), ('openllmetry', 'observability'),
  ('agentops', 'observability'), ('literal-ai', 'observability'),
  ('log10', 'observability'), ('openlit', 'observability'),
  ('honeyhive', 'observability'), ('phospho', 'observability'),
  -- Data Pipelines
  ('airflow', 'data-pipelines'), ('prefect', 'data-pipelines'),
  ('dagster', 'data-pipelines'), ('luigi', 'data-pipelines'),
  ('mage-ai', 'data-pipelines'), ('fivetran', 'data-pipelines'),
  ('airbyte', 'data-pipelines'), ('stitch', 'data-pipelines'),
  ('singer', 'data-pipelines'), ('apache-beam', 'data-pipelines'),
  ('spark', 'data-pipelines'), ('flink', 'data-pipelines'),
  ('kafka-connect', 'data-pipelines'), ('temporal', 'data-pipelines'),
  ('kestra', 'data-pipelines'),
  -- Code Generation
  ('github-copilot', 'code-generation'), ('cursor', 'code-generation'),
  ('codeium', 'code-generation'), ('tabnine', 'code-generation'),
  ('aider', 'code-generation'), ('continue-dev', 'code-generation'),
  ('codestral', 'code-generation'), ('starcoder2', 'code-generation'),
  ('devin', 'code-generation'), ('codex', 'code-generation'),
  ('bolt-new', 'code-generation'), ('replit-agent', 'code-generation'),
  ('windsurf', 'code-generation'), ('qodo', 'code-generation'),
  ('sourcegraph-cody', 'code-generation'),
  -- Image Generation
  ('dall-e-3', 'image-generation'), ('midjourney', 'image-generation'),
  ('stable-diffusion-xl', 'image-generation'), ('flux', 'image-generation'),
  ('imagen-3', 'image-generation'), ('leonardo-ai', 'image-generation'),
  ('ideogram', 'image-generation'), ('adobe-firefly', 'image-generation'),
  ('playground-v3', 'image-generation'), ('recraft-v3', 'image-generation'),
  ('comfyui', 'image-generation'), ('automatic1111', 'image-generation'),
  ('fooocus', 'image-generation'), ('invoke-ai', 'image-generation'),
  ('replicate-sdxl', 'image-generation'),
  -- Search Engines
  ('serper', 'search-engines'), ('algolia', 'search-engines'),
  ('meilisearch', 'search-engines'), ('you-search', 'search-engines'),
  ('searxng', 'search-engines'), ('jina-search', 'search-engines'),
  ('opensearch', 'search-engines'), ('zinc-search', 'search-engines'),
  ('manticore', 'search-engines'), ('bing-search-api', 'search-engines'),
  ('google-custom-search', 'search-engines'),
  -- Automation Platforms
  ('activepieces', 'automation-platforms'), ('pipedream', 'automation-platforms'),
  ('tray-io', 'automation-platforms'), ('workato', 'automation-platforms'),
  ('power-automate', 'automation-platforms'), ('ifttt', 'automation-platforms'),
  ('huginn', 'automation-platforms'), ('node-red', 'automation-platforms'),
  ('windmill', 'automation-platforms'), ('automatisch', 'automation-platforms'),
  ('trigger-dev', 'automation-platforms'), ('hatchet', 'automation-platforms'),
  -- Security Tools
  ('semgrep', 'security-tools'), ('checkov', 'security-tools'),
  ('bandit', 'security-tools'), ('dependabot', 'security-tools'),
  ('codeql', 'security-tools'), ('grype', 'security-tools'),
  ('falco', 'security-tools'), ('osv-scanner', 'security-tools'),
  ('prowler', 'security-tools'), ('nuclei', 'security-tools'),
  ('wiz', 'security-tools'), ('crowdstrike', 'security-tools')
) AS v(skill_slug, tt_slug)
JOIN skills s ON s.slug = v.skill_slug
JOIN tool_types tt ON tt.slug = v.tt_slug
ON CONFLICT DO NOTHING;

-- Add existing tools to search-engines and automation-platforms to boost those categories
INSERT INTO skill_tool_types (skill_id, tool_type_id)
SELECT s.id, tt.id
FROM (VALUES
  ('brave-search-mcp', 'search-engines'), ('tavily-mcp', 'search-engines'),
  ('exa-mcp-server', 'search-engines'), ('perplexity-mcp', 'search-engines'),
  ('zapier-mcp', 'automation-platforms'), ('make-mcp', 'automation-platforms'),
  ('n8n-mcp', 'automation-platforms'),
  -- Add observability existing tools
  ('datadog-mcp', 'observability'), ('grafana-mcp', 'observability'),
  ('pagerduty-mcp', 'observability'),
  -- Add existing tools to data-pipelines
  ('dbt-mcp', 'data-pipelines'), ('snowflake-mcp', 'data-pipelines'),
  ('bigquery-mcp', 'data-pipelines')
) AS v(skill_slug, tt_slug)
JOIN skills s ON s.slug = v.skill_slug
JOIN tool_types tt ON tt.slug = v.tt_slug
ON CONFLICT DO NOTHING;
