-- ToolRoute Migration 022: Additional Workflow Challenges
-- Expands the challenge catalog across finance, legal, customer-support,
-- marketing, content, operations, and dev-ops categories.

INSERT INTO workflow_challenges (slug, title, description, objective, difficulty, category, expected_steps, expected_tools, time_limit_minutes, cost_ceiling_usd, example_deliverable, evaluation_criteria, reward_multiplier, max_submissions) VALUES

('financial-report-analysis',
 'Financial Report Analysis',
 'Given a company''s quarterly earnings report, extract key financial metrics (revenue, net income, EPS, YoY growth), identify notable trends, and produce a structured executive summary with risk flags.',
 'Deliver a structured JSON report containing: 1) Key metrics table (revenue, net income, EPS, YoY growth for current and prior quarter), 2) Trend analysis highlighting sequential and year-over-year changes, 3) Risk flags with severity ratings for any concerning metrics, 4) A 3-paragraph executive summary suitable for a board deck.',
 'intermediate', 'finance', 4, 2, 20, 0.04,
 'Gold submission: All four key metrics extracted accurately, YoY growth calculated correctly, 2+ meaningful risk flags identified with evidence, concise executive summary, delivered under $0.02 cost using 2 tools.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100),

('contract-clause-review',
 'Contract Clause Review',
 'Review a SaaS contract for risky clauses (auto-renewal, liability caps, data ownership, termination penalties). Flag each risk with severity, quote the clause, and suggest alternative language.',
 'Deliver a structured risk report: 1) List of flagged clauses with clause text, section reference, risk category, and severity (critical/high/medium/low), 2) For each flagged clause, a plain-English explanation of why it is risky, 3) Suggested alternative language for each critical and high-severity clause, 4) An overall contract risk score (1-10) with recommendation to sign, negotiate, or reject.',
 'advanced', 'legal', 5, 2, 25, 0.05,
 'Gold submission: 5+ risky clauses identified with accurate section references, severity ratings justified, alternative language that is legally sound, overall risk score with clear rationale, under $0.03 cost.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100),

('customer-support-triage',
 'Customer Support Triage',
 'Process 15 incoming support tickets. Classify each by category (billing, technical, feature-request, bug), urgency (critical/high/medium/low), and suggested routing (tier-1, tier-2, engineering, billing-team). Produce a prioritized queue.',
 'Deliver a structured triage report: 1) Prioritized ticket queue sorted by urgency, 2) Each ticket classified with category, urgency, routing destination, and a one-line rationale, 3) Summary statistics (count by category, count by urgency), 4) Any tickets flagged for potential escalation with reasoning.',
 'beginner', 'customer-support', 3, 1, 15, 0.02,
 'Gold submission: All 15 tickets classified correctly, urgency ratings consistent and justified, routing matches category/urgency matrix, clear prioritized queue, delivered under $0.01 cost with 1 tool.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100),

('marketing-campaign-brief',
 'Marketing Campaign Brief',
 'Research a target market, analyze 3 competitor campaigns, and produce a complete campaign brief including: audience persona, messaging pillars, channel strategy, budget allocation, and 3 creative concepts with headlines.',
 'Deliver a full campaign brief document: 1) Target audience persona with demographics, psychographics, and pain points, 2) Competitor campaign analysis (3 competitors with strategy summary and gaps), 3) 3 messaging pillars with supporting proof points, 4) Channel strategy with recommended budget split across channels, 5) 3 creative concepts each with a headline, tagline, visual direction, and primary CTA.',
 'intermediate', 'marketing', 5, 3, 30, 0.06,
 'Gold submission: Well-researched persona backed by data, competitor analysis with actionable insights, messaging pillars that differentiate, realistic budget allocation, creative concepts that are specific and on-brand, under $0.04 cost.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100),

('compliance-audit-checklist',
 'Compliance Audit Checklist',
 'Audit a web application against GDPR and SOC 2 requirements. Check privacy policy completeness, data retention policies, consent mechanisms, access controls, and audit logging. Produce a compliance scorecard with pass/fail/partial per requirement and remediation steps.',
 'Deliver a compliance scorecard: 1) GDPR requirements checklist (consent, right to erasure, data portability, breach notification, DPO designation, etc.) with pass/fail/partial status, 2) SOC 2 controls checklist (access controls, encryption, monitoring, incident response, vendor management) with pass/fail/partial status, 3) For each failing or partial item, specific remediation steps with effort estimate (hours), 4) Overall compliance readiness percentage and prioritized remediation roadmap.',
 'expert', 'legal', 7, 3, 45, 0.10,
 'Gold submission: 15+ GDPR requirements and 10+ SOC 2 controls evaluated, accurate pass/fail assessments with evidence, actionable remediation steps with realistic effort estimates, prioritized roadmap, under $0.06 cost using 3 tools.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100),

('social-media-content-calendar',
 'Social Media Content Calendar',
 'Create a 2-week social media content calendar for a B2B SaaS company. Include 3 posts per day across LinkedIn, Twitter/X, and one other platform. Each post needs: platform, date/time, copy text, hashtags, and a content type tag (educational, promotional, engagement, thought-leadership).',
 'Deliver a structured content calendar: 1) 14 days x 3 posts = 42 total posts across LinkedIn, Twitter/X, and one additional platform, 2) Each post includes platform, scheduled date/time, full copy text (platform-appropriate length), 3-5 hashtags, and content type tag, 3) Content mix analysis showing distribution across content types, 4) Posting schedule optimized for each platform''s peak engagement times.',
 'beginner', 'content', 4, 2, 20, 0.03,
 'Gold submission: Full 42 posts with platform-appropriate copy, varied content types, strategic hashtag usage, optimal posting times, good mix of educational and engagement content, under $0.02 cost.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100),

('hr-onboarding-workflow',
 'HR Onboarding Workflow',
 'Design a complete employee onboarding workflow for a 50-person tech company. Include: pre-start checklist, Day 1 schedule, Week 1 learning plan, tool access provisioning list, buddy assignment criteria, and 30/60/90-day milestone checklist. Output as structured JSON.',
 'Deliver a structured JSON onboarding workflow: 1) Pre-start checklist (equipment, accounts, welcome packet, etc.), 2) Detailed Day 1 schedule with times and responsible parties, 3) Week 1 learning plan with daily themes and resources, 4) Tool access provisioning list with tool name, access level, and provisioning owner, 5) Buddy assignment criteria and matching algorithm, 6) 30/60/90-day milestone checklist with measurable success criteria for each milestone.',
 'intermediate', 'operations', 5, 2, 25, 0.04,
 'Gold submission: Comprehensive workflow covering all 6 sections, realistic for a 50-person tech company, milestones are measurable and specific, JSON is well-structured and machine-parseable, under $0.03 cost.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100),

('incident-response-playbook',
 'Incident Response Playbook',
 'Create an incident response playbook for a production outage. Include: severity classification matrix, escalation paths, communication templates (internal + external), root cause analysis template, post-mortem format, and automated monitoring checks to prevent recurrence. Must be specific enough to follow during a 3am outage.',
 'Deliver a complete incident response playbook: 1) Severity matrix (SEV1-SEV4) with criteria, response time SLAs, and on-call expectations, 2) Escalation paths per severity with contact roles and escalation triggers, 3) Communication templates: internal status update, customer-facing status page, executive summary, 4) Root cause analysis template with 5-Whys structure and contributing factors, 5) Post-mortem format with timeline, impact assessment, action items, and follow-up schedule, 6) Monitoring checks to add post-incident with alert thresholds and runbook links.',
 'expert', 'dev-ops', 6, 3, 40, 0.08,
 'Gold submission: Playbook specific enough to follow at 3am, severity matrix with clear thresholds, communication templates ready to fill in, post-mortem format used by real SRE teams, monitoring checks with concrete alert conditions, under $0.05 cost using 3 tools.',
 '{"completeness": 0.35, "quality": 0.35, "efficiency": 0.30}',
 3.0, 100);
